import {useEffect,useMemo,useRef,useState} from 'react';
import {Search,Bookmark,SlidersHorizontal,GitCompareArrows,ArrowUpRight,ChevronRight,X,Check,Download,Upload,Grid2X2,List,Scan,Shapes,Type,Palette,Grid3X3,Sparkles,Brain,Compass,Component,Layers,Waves,Smartphone,Accessibility,Blocks,FlaskConical,TextCursorInput,ChartNoAxesColumn,Code2,BookOpen,PanelLeftClose,Menu,Plus,Trash2,RotateCcw,FolderHeart,ExternalLink,Command,Info} from 'lucide-react';
import {categories,modules,featuredIds,getCategory,getModule,kinds,type Module,type Kind} from './catalog';
import {sources} from './sources';
import {Demo,Preview,defaultConfig,type DemoConfig} from './demos';
import {download,loadData,storageKey,validateData,type PersonalData} from './storage';
const icons:Record<string,typeof Scan>={Scan,Shapes,Type,Palette,Grid3X3,Sparkles,Brain,Compass,Component,Layers,Waves,Smartphone,Accessibility,Blocks,FlaskConical,TextCursorInput,ChartNoAxesColumn,Code2};
const initial=loadData();
type View='catalog'|'favorites'|'lab'|'compare'|'sources';
export default function App(){
 const [view,setView]=useState<View>('catalog'),[category,setCategory]=useState('all'),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[sort,setSort]=useState('curated'),[list,setList]=useState(false),[limit,setLimit]=useState(12),[data,setData]=useState<PersonalData>(initial.data),[storageIssue,setStorageIssue]=useState(initial.issue),[toast,setToast]=useState(''),[compare,setCompare]=useState<string[]>([]),[selected,setSelected]=useState<Module|undefined>(),[mobileMenu,setMobileMenu]=useState(false),[labId,setLabId]=useState('composition-1'),[labMode,setLabMode]=useState('module');
 const [smallScreen,setSmallScreen]=useState(()=>matchMedia('(max-width: 760px)').matches);
 const sidebarRef=useRef<HTMLElement>(null),menuRef=useRef<HTMLButtonElement>(null);
 const searchRef=useRef<HTMLInputElement>(null),dialogRef=useRef<HTMLDialogElement>(null),importRef=useRef<HTMLInputElement>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),dirty=useRef(false);
 useEffect(()=>{const media=matchMedia('(max-width: 760px)');const update=()=>{setSmallScreen(media.matches);if(!media.matches)setMobileMenu(false)};media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{if(!mobileMenu||!smallScreen)return;sidebarRef.current?.querySelector<HTMLButtonElement>('button')?.focus();const keys=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMobileMenu(false);return}if(e.key!=='Tab')return;const all=Array.from(sidebarRef.current?.querySelectorAll<HTMLButtonElement>('button:not([disabled])')||[]);const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);menuRef.current?.focus()}},[mobileMenu,smallScreen]);
 const notify=(s:string)=>{setToast(s);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),4000)};
 const changeData=(f:(d:PersonalData)=>PersonalData)=>{dirty.current=true;setData(f)};
 useEffect(()=>{if(!dirty.current)return;try{localStorage.setItem(storageKey,JSON.stringify(data));setStorageIssue('')}catch{setStorageIssue('Браузер не смог сохранить изменения. Экспортируйте отбор, чтобы сохранить текущие данные.')}},[data]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();if(dialogRef.current?.open)return;setView('catalog');setTimeout(()=>searchRef.current?.focus(),0)}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('keydown',key);if(toastTimer.current)clearTimeout(toastTimer.current)}},[]);
 useEffect(()=>{const read=()=>{const match=location.hash.match(/^#module=(.+)$/);setSelected(match?getModule(decodeURIComponent(match[1])):undefined)};read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read)},[]);
 useEffect(()=>{const dlg=dialogRef.current;if(selected&&!dlg?.open)dlg?.showModal();else if(!selected&&dlg?.open)dlg.close()},[selected]);
 useEffect(()=>setLimit(12),[category,query,kind,sort,view]);
 const open=(m:Module)=>{location.hash=`module=${m.id}`;setSelected(m)};
 const close=()=>{history.replaceState(null,'',location.pathname+location.search);setSelected(undefined)};
 const navigate=(v:View,c='all')=>{setView(v);setCategory(c);setQuery('');setKind('all');setMobileMenu(false);window.scrollTo({top:0,behavior:'instant'})};
 const toggleFavorite=(m:Module)=>{const exists=data.favorites.includes(m.id);changeData(d=>({...d,favorites:exists?d.favorites.filter(id=>id!==m.id):[...d.favorites,m.id]}));notify(exists?'Модуль удалён из отбора':'Модуль добавлен в ваш отбор')};
 const toggleCompare=(m:Module)=>{if(compare.includes(m.id))setCompare(a=>a.filter(id=>id!==m.id));else if(compare.length<3)setCompare(a=>[...a,m.id]);else notify('Для сравнения можно выбрать до трёх модулей')};
 const filtered=useMemo(()=>{const q=query.toLocaleLowerCase('ru').replace(/ё/g,'е').trim();let a=modules.filter(m=>(view!=='favorites'||data.favorites.includes(m.id))&&(category==='all'||m.category===category)&&(kind==='all'||m.kind===kind)&&(!q||[m.title,m.summary,m.example,...m.rules,...m.tags].join(' ').toLocaleLowerCase('ru').replace(/ё/g,'е').includes(q)));if(sort==='title')a.sort((a,b)=>a.title.localeCompare(b.title,'ru'));else if(sort==='category')a.sort((a,b)=>categories.findIndex(c=>c.id===a.category)-categories.findIndex(c=>c.id===b.category));else a.sort((a,b)=>{const ai=featuredIds.indexOf(a.id),bi=featuredIds.indexOf(b.id);return(ai<0?999:ai)-(bi<0?999:bi)});return a},[view,data.favorites,category,kind,query,sort]);
 const exportPersonal=()=>{download('design-atlas-my-collection.json',JSON.stringify({...data,exportedAt:new Date().toISOString()},null,2));notify('Отбор, заметки и настройки экспортированы')};
 const exportMarkdown=()=>{const text='# Мой Design Atlas\n\n'+data.favorites.map(id=>getModule(id)!).map(m=>`## ${m.title}\n\n${m.summary}\n\n${m.rules.map(s=>'- '+s).join('\n')}\n\nОграничение: ${m.pitfall}\n\nПример: ${m.example}\n\nИсточник / чтение: [${sources[m.source].title}](${sources[m.source].url})\n\n${data.notes[m.id]?'Моя заметка: '+data.notes[m.id]+'\n\n':''}`).join('');download('my-design-atlas.md',text,'text/markdown;charset=utf-8');notify('Ваш отбор экспортирован в Markdown')};
 const importPersonal=async(file:File)=>{try{if(file.size>10_000_000)throw new Error('Файл слишком большой: предел 10 MB.');const incoming=validateData(JSON.parse(await file.text()));changeData(d=>({...incoming,favorites:[...new Set([...d.favorites,...incoming.favorites])],notes:{...d.notes,...incoming.notes},checked:{...d.checked,...incoming.checked}}));notify('Отбор объединён. Заметки из файла обновлены.')}catch(e){notify(e instanceof Error?e.message:'Не удалось импортировать файл')}finally{if(importRef.current)importRef.current.value=''}};
 const cfg=(patch:Partial<DemoConfig>)=>changeData(d=>({...d,config:{...d.config,...patch}}));
 const labModule=getModule(labId)!;
 return <div className={`app-shell ${mobileMenu?'menu-open':''}`}>
 <a className="skip-link" href="#main">К содержанию</a>
 {mobileMenu&&<button className="sidebar-shade" aria-label="Закрыть меню" onClick={()=>setMobileMenu(false)}/>}
 <aside ref={sidebarRef} className="sidebar" aria-label="Библиотека" inert={smallScreen&&!mobileMenu}><button className="brand" onClick={()=>navigate('catalog')} aria-label="Design Atlas — каталог"><span className="brand-mark"><i/><i/><i/><i/></span><span>design<span className="brand-slash">/</span>atlas<small>ЛИЧНАЯ БИБЛИОТЕКА</small></span></button><div className="sidebar-main"><nav className="primary-nav"><button className={view==='catalog'&&category==='all'?'active':''} onClick={()=>navigate('catalog')}><Grid2X2 size={18}/>Все модули<span>{modules.length}</span></button><button className={view==='favorites'?'active':''} onClick={()=>navigate('favorites')}><Bookmark size={18}/>Мой отбор<span>{data.favorites.length}</span></button><button className={view==='lab'?'active':''} onClick={()=>navigate('lab')}><SlidersHorizontal size={18}/>Лаборатория</button><button className={view==='compare'?'active':''} onClick={()=>navigate('compare')}><GitCompareArrows size={18}/>Сравнение<span>{compare.length}</span></button></nav><p className="nav-label">ИССЛЕДОВАТЬ</p><nav className="category-nav">{categories.map(c=>{const Icon=icons[c.icon];return <button className={view==='catalog'&&category===c.id?'active':''} key={c.id} onClick={()=>navigate('catalog',c.id)}><Icon size={17}/>{c.short}<span>{modules.filter(m=>m.category===c.id).length}</span></button>})}</nav><button className={`sources-nav ${view==='sources'?'active':''}`} onClick={()=>navigate('sources')}><BookOpen size={17}/>Источники и метод</button></div><div className="sidebar-footer"><div className="local-symbol"><FolderHeart size={20}/></div><div><strong>Ваша территория дизайна</strong><span>Сохраняется на устройстве</span></div></div></aside>
 <div className="workspace" inert={smallScreen&&mobileMenu}><header className="topbar"><div className="topbar-path"><button ref={menuRef} className="mobile-menu icon-btn" onClick={()=>setMobileMenu(v=>!v)} aria-label="Открыть меню"><Menu size={20}/></button><span>Моя библиотека</span><ChevronRight size={14}/><strong>{view==='lab'?'Лаборатория':view==='compare'?'Сравнение':view==='favorites'?'Мой отбор':view==='sources'?'Источники':category==='all'?'Обзор':getCategory(category).short}</strong></div><div className="topbar-right"><span className="local-pill"><span/>Локально</span><button className="icon-btn" onClick={exportPersonal} aria-label="Экспортировать личный отбор" title="Экспортировать личный отбор"><Download size={18}/></button><button className="avatar" onClick={()=>navigate('favorites')} aria-label="Открыть личный отбор">Я</button></div></header>
 <main id="main" className="main-content">
 {storageIssue&&<div className="storage-warning" role="alert"><Info size={18}/>{storageIssue}<button onClick={exportPersonal}>Экспортировать</button></div>}
 {(view==='catalog'||view==='favorites')&&<><div className="page-intro"><div><div className="eyebrow"><span className="tiny-square"/> DESIGN ATLAS / {view==='favorites'?'COLLECTION':'EXPLORE'}</div><h1>{view==='favorites'?'Мой отбор':category==='all'?'Библиотека дизайна':getCategory(category).title}<span>.</span></h1><p>{view==='favorites'?'Идеи, которые вы хотите забрать в свои проекты.':category==='all'?'Правила, направления и паттерны. Смотрите, пробуйте, выбирайте своё.':getCategory(category).description+'.'}</p></div><div className="intro-tools">{view==='favorites'?<><button className="secondary-btn" onClick={exportPersonal}><Download size={16}/>JSON</button><button className="secondary-btn" onClick={exportMarkdown}>Markdown</button><button className="secondary-btn" onClick={()=>importRef.current?.click()}><Upload size={16}/>Импорт</button></>:<button className="intro-feature" onClick={()=>open(getModule('composition-2')!)}><span>ПРИЁМ В ФОКУСЕ</span><strong>Красота пропорций</strong><small>Исследовать золотое сечение <ArrowUpRight size={14}/></small><i>φ</i></button>}</div></div>
 <div className="view-tabs"><button className={view==='catalog'?'active':''} onClick={()=>navigate('catalog')}>Каталог <span>{modules.length}</span></button><button className={view==='favorites'?'active':''} onClick={()=>navigate('favorites')}>Мой отбор <span>{data.favorites.length}</span></button><button onClick={()=>navigate('lab')}>Лаборатория <span className="live-badge">LIVE</span></button><p>От идеи до работающего интерфейса</p></div>
 <div className="filter-toolbar"><label className="catalog-search"><Search size={19}/><input ref={searchRef} aria-label="Поиск модулей" placeholder="Найти правило, стиль или паттерн…" value={query} onChange={e=>setQuery(e.target.value)}/>{query?<button aria-label="Очистить поиск" onClick={()=>setQuery('')}><X size={15}/></button>:<kbd>⌘ K</kbd>}</label><label className="filter-select"><SlidersHorizontal size={16}/><span className="sr-only">Тип модуля</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Все типы</option>{Object.entries(kinds).map(([id,s])=><option key={id} value={id}>{s}</option>)}</select></label><label className="sort-select"><span className="sr-only">Сортировка</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="curated">Подборка Atlas</option><option value="title">По названию</option><option value="category">По категориям</option></select></label><div className="layout-toggle"><button className={!list?'active':''} aria-label="Показать сеткой" aria-pressed={!list} onClick={()=>setList(false)}><Grid2X2 size={17}/></button><button className={list?'active':''} aria-label="Показать списком" aria-pressed={list} onClick={()=>setList(true)}><List size={19}/></button></div></div>
 <div className="category-chips"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>Все модули</button>{['composition','styles','motion','native','type','color','a11y','components'].map(id=>{const c=getCategory(id);const Icon=icons[c.icon];return <button className={category===id?'active':''} key={id} onClick={()=>setCategory(id)}><Icon size={14}/>{c.short}</button>})}</div>
 <div className="result-heading"><h2>{category==='all'&&!query&&kind==='all'?(view==='favorites'?'Сохранённые модули':'Начните с любопытства'):query?`Результаты для «${query}»`:category==='all'?kinds[kind as Kind]:getCategory(category).title}</h2><span>{filtered.length} из {view==='favorites'?data.favorites.length:modules.length} модулей</span></div>
 {filtered.length?<div className={`module-grid ${list?'list-view':''}`}>{filtered.slice(0,limit).map(m=><article className="module-card" key={m.id}><div className="card-preview" style={{background:getCategory(m.category).color}}><button className="preview-open" onClick={()=>open(m)} aria-label={`Открыть ${m.title}`}><Preview m={m}/></button><span className={`kind-badge kind-${m.kind}`}>{kinds[m.kind]}</span><button className={`save-button ${data.favorites.includes(m.id)?'saved':''}`} onClick={()=>toggleFavorite(m)} aria-label={`${data.favorites.includes(m.id)?'Убрать из отбора':'В отбор'}: ${m.title}`} aria-pressed={data.favorites.includes(m.id)}><Bookmark size={17} fill={data.favorites.includes(m.id)?'currentColor':'none'}/></button></div><div className="card-body"><span className="card-category">{getCategory(m.category).short}</span><button className="card-title" onClick={()=>open(m)}><h3>{m.title}</h3><ArrowUpRight size={18}/></button><p>{m.summary}</p><div className="card-footer"><button className="try-button" onClick={()=>open(m)}><span className="live-dot"/>Попробовать</button><button className={compare.includes(m.id)?'compare-button selected':'compare-button'} onClick={()=>toggleCompare(m)} aria-label={`${compare.includes(m.id)?'Убрать из сравнения':'Сравнить'}: ${m.title}`} aria-pressed={compare.includes(m.id)}><GitCompareArrows size={17}/></button></div></div></article>)}</div>:<div className="empty-state"><FolderHeart size={40}/><h2>{view==='favorites'&&!query&&category==='all'&&kind==='all'?'Ваш отбор начинается здесь':'Ничего не найдено'}</h2><p>{view==='favorites'&&!query?'Сохраняйте понравившиеся модули значком закладки.':'Попробуйте другое название или сбросьте фильтры.'}</p><button className="primary-btn" onClick={()=>{if(view==='favorites'&&!query)navigate('catalog');else{setCategory('all');setKind('all');setQuery('')}}}>{view==='favorites'&&!query?'Исследовать каталог':'Сбросить фильтры'}</button></div>}
 {filtered.length>limit&&<div className="load-more"><button className="secondary-btn" onClick={()=>setLimit(v=>v+12)}><Plus size={16}/>Показать ещё {Math.min(12,filtered.length-limit)}</button><span>Показано {Math.min(limit,filtered.length)} из {filtered.length}</span></div>}<div className="catalog-note"><Info size={16}/><p>Стандарт задаёт требования. Эвристика помогает искать решение. Приём и направление дают выразительный язык. Применимость проверяйте в своей задаче.</p><button onClick={()=>navigate('sources')}>О методе<ArrowUpRight size={14}/></button></div></>}
 {view==='lab'&&<><div className="page-intro"><div><div className="eyebrow">DESIGN ATLAS / PLAYGROUND</div><h1>Лаборатория<span>.</span></h1><p>Меняйте параметры и смотрите, как они влияют на интерфейс.</p></div><button className="secondary-btn" onClick={()=>cfg(defaultConfig)}><RotateCcw size={16}/>Сбросить настройки</button></div><div className="lab-layout"><section className="lab-settings"><h2>Ваши параметры</h2><label className="lab-color">Акцент<input type="color" value={data.config.accent} onChange={e=>cfg({accent:e.target.value})}/><code>{data.config.accent}</code></label>{[['radius','Радиус',0,40,'px'],['spacing','Интервалы',8,32,'px'],['duration','Длительность',100,1600,'ms']].map(([key,label,min,max,unit])=><label className="range-control" key={key}><span>{label}<b>{data.config[key as 'radius'|'spacing'|'duration']} {unit}</b></span><input type="range" min={min} max={max} step={key==='duration'?10:1} value={data.config[key as 'radius'|'spacing'|'duration']} onChange={e=>cfg({[key]:+e.target.value})}/></label>)}<label className="select-control">Платформа<select value={data.config.platform} onChange={e=>cfg({platform:e.target.value})}><option value="web">Web</option><option value="ios">iOS</option><option value="android">Android</option><option value="desktop">Desktop</option></select></label><label className="check-control"><input type="checkbox" checked={data.config.reduced} onChange={e=>cfg({reduced:e.target.checked})}/>Уменьшить движение</label><button className="secondary-btn" onClick={()=>{download('design-atlas-tokens.css',`:root {\n  --accent: ${data.config.accent};\n  --radius: ${data.config.radius}px;\n  --space: ${data.config.spacing}px;\n  --duration: ${data.config.duration}ms;\n}\n`,'text/css');notify('CSS-токены экспортированы')}}><Download size={16}/>Экспорт CSS-токенов</button><p className="demo-note">Параметры сохранены локально. Каждый пример использует только подходящие ему настройки.</p></section><section className="lab-canvas"><div className="lab-mode">{[['module','Модули'],['native','Платформы'],['tokens','Токены']].map(([id,s])=><button key={id} className={labMode===id?'active':''} onClick={()=>setLabMode(id)}>{s}</button>)}</div>{labMode==='module'?<><label className="lab-module-select">Модуль<select value={labId} onChange={e=>setLabId(e.target.value)}>{categories.map(c=><optgroup key={c.id} label={c.title}>{modules.filter(m=>m.category===c.id).map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</optgroup>)}</select></label><div className="lab-demo"><Demo key={labId} m={labModule} config={data.config}/></div><button className="text-btn lab-detail" onClick={()=>open(labModule)}>Правила и ограничения модуля <ArrowUpRight size={15}/></button></>:<div className="lab-demo"><Demo key={labMode} m={getModule(labMode==='native'?'native-5':'systems-1')!} config={data.config}/></div>}</section></div></>}
 {view==='compare'&&<><div className="page-intro"><div><div className="eyebrow">DESIGN ATLAS / SIDE BY SIDE</div><h1>Сравнение<span>.</span></h1><p>До трёх модулей рядом: характер, применение и ограничения.</p></div>{compare.length>0&&<button className="secondary-btn" onClick={()=>setCompare([])}><Trash2 size={16}/>Очистить</button>}</div>{compare.length?<div className="comparison-grid" style={{gridTemplateColumns:`repeat(${compare.length},minmax(0,1fr))`}}>{compare.map(id=>getModule(id)!).map(m=><article className="comparison-column" key={m.id}><div className="comparison-preview" style={{background:getCategory(m.category).color}}><Preview m={m}/><button className="icon-btn" onClick={()=>toggleCompare(m)} aria-label={`Убрать ${m.title}`}><X size={17}/></button></div><div className="comparison-content"><span className="card-category">{getCategory(m.category).title}</span><h2>{m.title}</h2><span className="comparison-kind">{kinds[m.kind]}</span><p>{m.summary}</p><h3>Как применять</h3><ul>{m.rules.map(s=><li key={s}>{s}</li>)}</ul><h3>Граница применения</h3><p>{m.pitfall}</p><h3>Пример</h3><p>{m.example}</p><button className="primary-btn" onClick={()=>open(m)}>Открыть пример</button><button className="secondary-btn" onClick={()=>toggleFavorite(m)}><Bookmark size={16}/>{data.favorites.includes(m.id)?'В вашем отборе':'В мой отбор'}</button></div></article>)}</div>:<div className="empty-state"><GitCompareArrows size={40}/><h2>Что будем сравнивать?</h2><p>Выберите до трёх модулей значком сравнения на карточках.</p><button className="primary-btn" onClick={()=>navigate('catalog')}>Выбрать модули</button></div>}</>}
 {view==='sources'&&<><div className="page-intro"><div><div className="eyebrow">DESIGN ATLAS / REFERENCES</div><h1>Источники и метод<span>.</span></h1><p>Проверенные ориентиры и границы этой библиотеки.</p></div><button className="secondary-btn" onClick={()=>{const escape=(x:string)=>'"'+x.replaceAll('"','""')+'"';const rows=modules.map(m=>[m.id,m.title,getCategory(m.category).title,kinds[m.kind],m.summary,m.rules.join(' • '),m.pitfall,m.example,sources[m.source].url]);download('design-atlas-catalog.csv','\uFEFF'+[['ID','Название','Категория','Тип','Смысл','Правила','Ограничения','Пример','Источник'],...rows].map(a=>a.map(escape).join(';')).join('\r\n'),'text/csv;charset=utf-8');notify('Полный каталог экспортирован в CSV')}}><Download size={16}/>Весь каталог · CSV</button></div><div className="method-panel"><div><span className="eyebrow">ОБЪЁМ БИБЛИОТЕКИ</span><strong>{modules.length}<small>модулей / {categories.length} разделов</small></strong></div><p>Это широкая, расширяемая карта дизайна, а не утверждение, что существует конечный список «всех правил». Объяснения и схемы написаны для этого каталога. Ссылка у модуля указывает на нормативную опору или дополнительное чтение; художественные адаптации и учебные пресеты не являются требованиями источника.</p></div><div className="method-types">{Object.entries(kinds).map(([id,title])=><div key={id}><span className={`kind-badge kind-${id}`}>{title}</span><p>{{standard:'Требование с областью применения, уровнем и исключениями. Проверяйте оригинальный критерий.',heuristic:'Полезный ориентир для выбора и оценки. Результат зависит от контекста.',technique:'Способ построить композицию или эффект. Применяйте осознанно.',style:'Визуальный язык. Он не гарантирует удобство или доступность.',practice:'Рабочий подход. Подстраивайте под продукт, команду и аудиторию.'}[id]}</p></div>)}</div><div className="source-list">{Object.entries(sources).map(([id,s])=><a key={id} href={s.url} target="_blank" rel="noreferrer"><span className="source-number">{String(Object.keys(sources).indexOf(id)+1).padStart(2,'0')}</span><div><h2>{s.title}</h2><p>{s.note}</p></div><ExternalLink size={17}/></a>)}</div><div className="local-explanation"><h2>Ваши данные</h2><p>Отбор, заметки, отметки правил и настройки хранятся в localStorage этого браузера и адреса. Очистка данных браузера может их удалить. Для переноса используйте JSON-экспорт; импорт объединяет закладки и обновляет одноимённые заметки из файла. Каталог и примеры доступны без интернета после запуска локального сервера. Внешние источники требуют соединения.</p><button className="secondary-btn" onClick={exportPersonal}><Download size={16}/>Сохранить резервную копию</button><button className="secondary-btn" onClick={()=>importRef.current?.click()}><Upload size={16}/>Импортировать отбор</button></div></>}
 <footer className="page-footer"><span>DESIGN ATLAS <b>©</b> 2026</span><p>Личная библиотека. Пространство для ваших решений.</p><button onClick={()=>navigate('sources')}>Источники</button></footer>
 </main></div>
 {compare.length>0&&view!=='compare'&&<div className="compare-tray"><span><GitCompareArrows size={18}/>Выбрано для сравнения <b>{compare.length}/3</b></span><div>{compare.map(id=><button key={id} onClick={()=>toggleCompare(getModule(id)!)} aria-label={`Убрать ${getModule(id)!.title}`}>{getModule(id)!.title}<X size={13}/></button>)}</div><button className="primary-btn" onClick={()=>navigate('compare')}>Сравнить</button><button className="icon-btn" onClick={()=>setCompare([])} aria-label="Очистить сравнение"><X size={18}/></button></div>}
 <dialog ref={dialogRef} className="module-dialog" aria-labelledby="module-title" onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}}}>
 {selected&&<><div className="dialog-top"><span>{getCategory(selected.category).title}<ChevronRight size={14}/>{kinds[selected.kind]}</span><button className="icon-btn" onClick={close} aria-label="Закрыть модуль"><X size={20}/></button></div><div className="dialog-heading"><div><span className="eyebrow">МОДУЛЬ / {selected.id.toUpperCase()}</span><h2 id="module-title">{selected.title}</h2><p>{selected.summary}</p></div><button className={`secondary-btn ${data.favorites.includes(selected.id)?'is-saved':''}`} onClick={()=>toggleFavorite(selected)}><Bookmark size={16} fill={data.favorites.includes(selected.id)?'currentColor':'none'}/>{data.favorites.includes(selected.id)?'В отборе':'В мой отбор'}</button></div><div className="dialog-body"><section className="dialog-demo"><div className="demo-section-header"><span><span className="live-dot"/>Живой пример</span><button className="text-btn" onClick={()=>{setLabId(selected.id);setLabMode('module');close();navigate('lab')}}>В лабораторию<ArrowUpRight size={15}/></button></div><Demo key={selected.id} m={selected} config={data.config}/></section><section className="module-info"><h3>Как применять</h3><p className="check-hint">Отметьте то, что хотите учитывать в проекте.</p><div className="rule-checklist">{selected.rules.map((rule,i)=><label key={i}><input type="checkbox" checked={(data.checked[selected.id]||[]).includes(i)} onChange={e=>{const id=selected.id;changeData(d=>({...d,checked:{...d.checked,[id]:e.target.checked?[...(d.checked[id]||[]),i]:(d.checked[id]||[]).filter(x=>x!==i)}}))}}/><span>{rule}</span></label>)}</div><div className="pitfall-box"><Info size={18}/><div><h3>Граница применения</h3><p>{selected.pitfall}</p></div></div><div className="example-box"><h3>В реальном интерфейсе</h3><p>{selected.example}</p></div><a className="module-source" href={sources[selected.source].url} target="_blank" rel="noreferrer"><BookOpen size={16}/><span><small>Источник / чтение по теме</small>{sources[selected.source].title}</span><ExternalLink size={15}/></a><label className="module-notes">Моя заметка<textarea value={data.notes[selected.id]||''} maxLength={5000} onChange={e=>{const id=selected.id,n=e.target.value;changeData(d=>({...d,notes:{...d.notes,[id]:n}}))}} placeholder="Где я хочу использовать этот подход…"/><small>Сохраняется на этом устройстве · до 5 000 знаков</small></label><button className="secondary-btn" onClick={()=>toggleCompare(selected)}><GitCompareArrows size={16}/>{compare.includes(selected.id)?'Убрать из сравнения':'Добавить к сравнению'}</button></section></div></>}
 </dialog>
 <input ref={importRef} className="sr-only" type="file" accept="application/json,.json" aria-label="Импорт JSON Design Atlas" onChange={e=>{const f=e.target.files?.[0];if(f)void importPersonal(f)}}/>
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}<button onClick={()=>setToast('')} aria-label="Закрыть уведомление"><X size={15}/></button></div>}
 </div>;
}
