import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,Bookmark,Check,Code2,Copy,Download,ExternalLink,Play,RotateCcw,Search,Square,X,Info,SlidersHorizontal,Library,Layers,Sparkles} from 'lucide-react';
import {components,getComponent,componentCategories,componentLibraries,componentFeatured,type ComponentDescriptor,type ComponentFile} from './component-catalog';
import type {PersonalData} from './storage';
import './components.css';
type Props={data:PersonalData;changeData:(f:(d:PersonalData)=>PersonalData)=>void;notify:(s:string)=>void;favoritesOnly?:boolean};
export default function ComponentsPage({data,changeData,notify,favoritesOnly=false}:Props){
 const [section,setSection]=useState('collection'),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[library,setLibrary]=useState('all'),[tech,setTech]=useState('all'),[format,setFormat]=useState('all'),[onlySaved,setOnlySaved]=useState(favoritesOnly),[limit,setLimit]=useState(12),[edition,setEdition]=useState('all');
 const [selected,setSelected]=useState<ComponentDescriptor|undefined>(()=>{const id=new URLSearchParams(location.hash.slice(1)).get('component');return id?getComponent(id):undefined});
 const [tab,setTab]=useState('demo'),[running,setRunning]=useState(false),[runId,setRunId]=useState(0),[viewport,setViewport]=useState('desktop'),[theme,setTheme]=useState('dark'),[file,setFile]=useState<ComponentFile>(),[code,setCode]=useState(''),[codeError,setCodeError]=useState(''),[previewError,setPreviewError]=useState(''),[loading,setLoading]=useState(false),[manualCopy,setManualCopy]=useState('');
 const dlg=useRef<HTMLDialogElement>(null),frame=useRef<HTMLIFrameElement>(null),manualRef=useRef<HTMLTextAreaElement>(null);
 const [reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
 const effectiveReduced=reduced||data.config.reduced;
 const [draft,setDraft]=useState<Record<string,string|number>>({}),[applied,setApplied]=useState<Record<string,string|number>>({});
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');const f=()=>setReduced(mq.matches);mq.addEventListener('change',f);return()=>mq.removeEventListener('change',f)},[]);
 useEffect(()=>{const read=()=>{const id=new URLSearchParams(location.hash.slice(1)).get('component');setSelected(id?getComponent(id):undefined)};window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read)},[]);
 useEffect(()=>{if(selected){if(!dlg.current?.open)dlg.current?.showModal();setTab('demo');setFile(selected.exportFiles?.find(f=>f.path===selected.entry));setPreviewError('');setManualCopy('');setDraft(data.components.presets[selected.id]||{});setApplied(data.components.presets[selected.id]||{});setRunning(!effectiveReduced&&!selected.heavy);setLoading(!effectiveReduced&&!selected.heavy)}else{dlg.current?.close();setRunning(false)}},[selected?.id]);
 useEffect(()=>{if(effectiveReduced)setRunning(false)},[effectiveReduced]);
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.source!==frame.current?.contentWindow||event.data?.id!==selected?.id||event.data?.atlasPreview!==true)return;if(event.data.type==='ready')setLoading(false);if(event.data.type==='error'){setLoading(false);setPreviewError(String(event.data.message).slice(0,500))}};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[selected?.id]);
 useEffect(()=>{if(!running||!selected||!loading)return;const t=setTimeout(()=>{setLoading(false);setPreviewError('Демо не подтвердило загрузку. Попробуйте перезапуск.')},15000);return()=>clearTimeout(t)},[running,runId,selected?.id,loading]);
 useEffect(()=>{setLimit(12)},[query,category,library,tech,format,onlySaved,edition]);
 useEffect(()=>{if(!file)return;const controller=new AbortController();setCode('');setCodeError('');fetch(file.url,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('Не удалось загрузить файл');return r.text()}).then(setCode).catch(e=>{if(e.name!=='AbortError')setCodeError(e.message)});return()=>controller.abort()},[file?.url]);
 useEffect(()=>{if(manualCopy){manualRef.current?.focus();manualRef.current?.select()}},[manualCopy]);
 const close=()=>{history.replaceState(null,'',location.pathname+location.search+'#components');setSelected(undefined);setRunning(false)};
 const open=(m:ComponentDescriptor)=>{location.hash='component='+encodeURIComponent(m.id);setSelected(m)};
 const save=(m:ComponentDescriptor)=>changeData(d=>({...d,components:{...d.components,favorites:d.components.favorites.includes(m.id)?d.components.favorites.filter(id=>id!==m.id):[...d.components.favorites,m.id]}}));
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);notify('Скопировано в буфер обмена')}catch{setManualCopy(text);notify('Буфер недоступен. Текст выделен для ручного копирования.')}};
 const copyFile=async(f:ComponentFile)=>{try{const r=await fetch(f.url);if(!r.ok)throw new Error('Файл недоступен');await copy(await r.text())}catch(e){notify(e instanceof Error?e.message:'Ошибка копирования')}};
 const filtered=useMemo(()=>components.filter(m=>(edition!=='new'||!!m.batch)&&(edition!=='extra'||!!m.extra)&&(!onlySaved||data.components.favorites.includes(m.id))&&(category==='all'||m.category===category)&&(library==='all'||m.library===library)&&(tech==='all'||m.technologies.includes(tech))&&(format==='all'||m.formats.includes(format))&&(!query||[m.title,m.description,m.name,componentCategories[m.category],m.library,...m.technologies].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>Number(!!b.batch)-Number(!!a.batch)||(componentFeatured.includes(a.id)?componentFeatured.indexOf(a.id):999)-(componentFeatured.includes(b.id)?componentFeatured.indexOf(b.id):999)),[edition,query,category,library,tech,format,onlySaved,data.components.favorites]);
 const start=()=>{setRunning(true);setLoading(true);setPreviewError('');setRunId(i=>i+1)};
 return <section className="component-market">
 <div className="component-intro"><div><div className="eyebrow"><Sparkles size={14}/> DESIGN ATLAS / COMPONENTS</div><h1>Дизайн, который<br/><em>можно забрать.</em></h1><p>{components.length} отобранный модуль. Настоящие анимации, интерактивность и исходники — для вашего следующего проекта.</p><div className="component-stat"><span><b>{components.length}</b> живых примеров</span><span><b>{new Set(components.map(m=>m.library)).size}</b> коллекций</span><span>React · Next.js · HTML/CSS</span></div></div><div className="component-feature shader-feature"><span className="feature-orbit orbit-one"/><span className="feature-orbit orbit-two"/><div className="feature-core">✦</div><span className="feature-coordinate">FORM / MOTION / INTERACTION</span><button onClick={()=>open(getComponent('paper-shaders-liquid-metal')!)}>Попробовать Liquid Metal <ArrowUpRight size={18}/></button><span className="feature-number">№ {String(components.length).padStart(3,'0')}</span></div></div>
 <div className="market-tabs"><button className={section==='collection'?'active':''} onClick={()=>setSection('collection')}><Layers size={16}/>Коллекция <span>{components.length}</span></button><button className={section==='libraries'?'active':''} onClick={()=>setSection('libraries')}><Library size={16}/>Библиотеки <span>{componentLibraries.length}</span></button><button className={section==='collection'&&onlySaved?'active':''} onClick={()=>{setOnlySaved(!onlySaved);setSection('collection')}}><Bookmark size={16}/>Мой отбор <span>{data.components.favorites.length}</span></button></div>
 {section==='libraries'?<div className="library-grid">{componentLibraries.map(l=><article key={l.id} style={{'--library-accent':l.color} as React.CSSProperties}><span className="library-monogram">{l.title.slice(0,1)}</span><span className="library-license">{l.license}</span><h2>{l.title}</h2><p>{l.description}</p><small>{l.note}</small><div><a href={l.url} target="_blank" rel="noreferrer">Открыть библиотеку <ExternalLink size={14}/></a><a href={l.licenseUrl} target="_blank" rel="noreferrer">Лицензия ↗</a></div></article>)}</div>:<>
 <div className="edition-chips" aria-label="Подборки компонентов">{[["all","Вся коллекция",components.length],["new","Новое",components.filter(m=>m.batch).length],["extra","Ещё 20 эффектов",components.filter(m=>m.extra).length]].map(([id,title,count])=><button key={id} aria-pressed={edition===id} className={edition===id?"active":""} onClick={()=>setEdition(String(id))}>{id!=="all"&&<Sparkles size={13}/>} {title} <span>{count}</span></button>)}<small>Новые фоны · физика · живые интерфейсы</small></div><div className="market-filters"><label className="catalog-search"><Search size={18}/><input placeholder="Найти эффект, компонент или библиотеку…" aria-label="Поиск компонентов" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Очистить поиск компонентов" onClick={()=>setQuery('')}><X size={16}/></button>}</label>{[[library,setLibrary,'Библиотека',[['all','Все библиотеки'],...componentLibraries.filter(l=>l.id!=='aceternity').map(l=>[l.id,l.title])]], [tech,setTech,'Технология',['all','CSS','Motion','GSAP','WebGL','Physics'].map(x=>[x,x==='all'?'Все технологии':x])],[format,setFormat,'Формат',['all','React','Next.js','HTML/CSS'].map(x=>[x,x==='all'?'Все форматы':x])]].map(([value,setter,label,options])=><label className="market-select" key={label as string}><span className="sr-only">{label as string}</span><select value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}>{(options as string[][]).map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>)}</div>
 <div className="category-chips">{Object.entries(componentCategories).map(([id,title])=><button key={id} className={category===id?'active':''} onClick={()=>setCategory(id)}>{title}</button>)}</div>
 <label className="motion-preference"><input type="checkbox" checked={effectiveReduced} disabled={reduced} onChange={e=>{const value=e.target.checked;changeData(d=>({...d,config:{...d.config,reduced:value}}))}}/>Уменьшить движение<span>Статические превью до ручного запуска</span></label>
 <div className="result-heading"><h2>{onlySaved?'Сохранённые компоненты':'Ваша следующая деталь'}</h2><span>{filtered.length} {filtered.length%100>=11&&filtered.length%100<=14?"компонентов":filtered.length%10===1?"компонент":filtered.length%10>=2&&filtered.length%10<=4?"компонента":"компонентов"}</span></div>
 <div className="component-grid">{filtered.slice(0,limit).map((m,i)=><article className="component-card" key={m.id}><div className="component-cover"><button className="component-poster" onClick={()=>open(m)} aria-label={'Открыть '+m.title}><img src={m.poster} alt={'Превью '+m.title} loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/><span className="poster-fallback"><Code2 size={30}/>{m.title}</span><span className="poster-play"><Play size={18} fill="currentColor"/></span></button>{m.batch&&<span className="component-new">NEW</span>}<span className="component-count">{String(components.indexOf(m)+1).padStart(2,'0')}</span><button className={'component-save '+(data.components.favorites.includes(m.id)?'saved':'')} aria-label={(data.components.favorites.includes(m.id)?'Убрать из отбора: ':'В отбор: ')+m.title} aria-pressed={data.components.favorites.includes(m.id)} onClick={()=>save(m)}><Bookmark size={17} fill={data.components.favorites.includes(m.id)?'currentColor':'none'}/></button><span className="component-library-label">{componentLibraries.find(l=>l.id===m.library)?.title}</span></div><div className="component-card-body"><span className="component-category">{componentCategories[m.category]}</span><button className="card-title" onClick={()=>open(m)}><h3>{m.title}</h3><ArrowUpRight size={18}/></button><p>{m.description}</p><div className="component-tags">{m.technologies.filter(t=>t!=='CSS'||m.technologies.length===1).map(t=><span key={t}>{t}</span>)}<span>{m.formats[0]}</span><span title={"Лицензия: "+m.license}>{m.license}</span>{m.heavy&&<span>{m.technologies.includes("Physics")?"Физика":"GPU"}</span>}<span title={m.keyboard+" "+m.mobile}>{/не реализован|не имеет|мышью|Правый клик/.test(m.keyboard)?"Указатель":m.keyboard?.includes("Декоративная")?"Анимация":"Клавиатура"}</span></div><div className="component-card-actions"><button onClick={()=>open(m)}><Play size={13}/>Попробовать</button><button onClick={()=>void copyFile(m.exportFiles.find(f=>f.path===m.entry)!)} aria-label={'Копировать исходник '+m.title}><Copy size={14}/>Код</button></div></div></article>)}</div>
 {!filtered.length&&<div className="empty-state"><Search size={36}/><h2>Пока пусто</h2><p>Измените фильтры или сохраните понравившиеся компоненты.</p><button className="secondary-btn" onClick={()=>{setQuery('');setCategory('all');setLibrary('all');setTech('all');setFormat('all');setOnlySaved(false);setEdition('all')}}>Показать всю коллекцию</button></div>}
 {filtered.length>limit&&<div className="load-more"><button className="secondary-btn" onClick={()=>setLimit(n=>n+12)}>Показать ещё {Math.min(12,filtered.length-limit)}</button></div>}
 <div className="component-bottom-note"><Info size={16}/><p>Исходники зафиксированы по ревизии. Демо запускаются отдельно; готовые комплекты включают зависимости, стили и лицензии.</p></div></>}
 <dialog ref={dlg} className="component-dialog" aria-labelledby="component-title" onCancel={e=>{e.preventDefault();close()}}>
 {selected&&<><div className="component-dialog-top"><span>{componentLibraries.find(l=>l.id===selected.library)?.title} / {componentCategories[selected.category]}</span><button className="icon-btn" aria-label="Закрыть компонент" onClick={close}><X size={20}/></button></div><div className="component-dialog-heading"><div><span className="eyebrow">ГОТОВЫЙ КОМПОНЕНТ / {selected.formats.join(' · ')}</span><h2 id="component-title">{selected.title}</h2><p>{selected.description}</p></div><button className="secondary-btn" onClick={()=>save(selected)}><Bookmark size={16}/>{data.components.favorites.includes(selected.id)?'В отборе':'В отбор'}</button></div>
 <div className="component-detail-tabs" role="tablist" aria-label="Раздел компонента">{[['demo','Демо'],['code','Код'],['install','Подключение'],['source','Источник']].map(([id,title])=><button key={id} role="tab" id={"component-tab-"+id} aria-controls="component-tab-panel" tabIndex={tab===id?0:-1} onKeyDown={e=>{const ids=["demo","code","install","source"];const n=ids.indexOf(id);const next=e.key==="ArrowRight"?ids[(n+1)%4]:e.key==="ArrowLeft"?ids[(n+3)%4]:e.key==="Home"?ids[0]:e.key==="End"?ids[3]:null;if(next){e.preventDefault();setTab(next);if(next!=="demo")setRunning(false);dlg.current?.querySelector<HTMLButtonElement>("#component-tab-"+next)?.focus()}}} aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>{setTab(id);if(id!=='demo')setRunning(false)}}>{title}</button>)}</div>
 <div id="component-tab-panel" role="tabpanel" aria-labelledby={"component-tab-"+tab}>
 {tab==='demo'&&<div className="component-demo-panel"><div className="component-demo-toolbar"><div><button className="small-btn" onClick={()=>running?setRunning(false):start()}>{running?<Square size={14}/>:<Play size={14}/>} {running?'Остановить':'Запустить'}</button><button className="small-btn" aria-label="Перезапустить демо" onClick={start}><RotateCcw size={14}/></button></div><div><label><span className="sr-only">Размер демо</span><select value={viewport} onChange={e=>setViewport(e.target.value)}><option value="desktop">Desktop</option><option value="mobile">Mobile · 390</option></select></label><label><span className="sr-only">Фон демо</span><select value={theme} onChange={e=>{setTheme(e.target.value);if(running)start()}}><option value="dark">Тёмный</option><option value="light">Светлый</option></select></label></div></div>
 <div className={'component-stage '+(viewport==='mobile'?'mobile-stage':'')}>
 {running?<><iframe key={runId} ref={frame} title={selected.title+' — интерактивное демо'} src={selected.preview+'?theme='+theme+'&settings='+encodeURIComponent(JSON.stringify(applied))} sandbox="allow-scripts" referrerPolicy="no-referrer" allow="" onLoad={()=>{}}/>{loading&&<span className="preview-loading">Загружаем демо…</span>}</>:<div className="component-paused"><img src={selected.poster} alt={'Статическое превью '+selected.title}/><div><button className="primary-btn" onClick={start}><Play size={17}/>Запустить демо</button><p>{effectiveReduced?'У вас включено уменьшение движения. Запуск — по вашему выбору.':selected.heavy?(selected.technologies.includes('Physics')?'Демо использует физический движок. Запустите, когда будете готовы.':'Эффект использует WebGL. Запустите, когда будете готовы.'):'Демо остановлено. Ресурсы освобождены.'}</p></div></div>}
 </div>{previewError&&<p className="preview-error" role="alert">{previewError}</p>}
 {!!selected.controls.length&&<div className="component-controls"><span><SlidersHorizontal size={15}/>Параметры оригинала</span>{selected.controls.map(c=><label key={c.key}>{c.label}{c.type==='number'?<><b>{draft[c.key]??c.default}</b><input type="range" min={c.min} max={c.max} step={c.step} value={draft[c.key]??c.default} onChange={e=>setDraft(p=>({...p,[c.key]:+e.target.value}))}/></>:<input type={c.type==='color'?'color':'text'} maxLength={180} value={draft[c.key]??c.default} onChange={e=>setDraft(p=>({...p,[c.key]:e.target.value}))}/>}</label>)}<button className="secondary-btn" onClick={()=>{setApplied(draft);changeData(d=>({...d,components:{...d.components,presets:{...d.components.presets,[selected.id]:draft}}}));start()}}>Применить</button><button className="text-btn" onClick={()=>{setDraft({});setApplied({});changeData(d=>({...d,components:{...d.components,presets:{...d.components.presets,[selected.id]:{}}}}));start()}}>Сбросить</button></div>}
 <div className="component-runtime-notes"><span>{selected.performance}</span><span>{selected.keyboard}</span><span>{selected.mobile}</span></div></div>}
 {tab==='code'&&<div className="component-code-panel"><div className="code-toolbar"><label>Файл<select aria-label="Файл компонента" value={file?.path||''} onChange={e=>setFile(selected.exportFiles.find(f=>f.path===e.target.value))}>{selected.exportFiles.filter(f=>!/\.(ttf|png|glb)$/.test(f.path)).map(f=><option key={f.path} value={f.path}>{f.path}</option>)}</select></label><button className="secondary-btn" disabled={!code} onClick={()=>void copy(code)}><Copy size={15}/>Копировать файл</button><button className="secondary-btn" onClick={()=>void copyFile(selected.exportFiles.find(f=>f.path===(selected.library==='uiverse'?selected.entry:'Example.tsx'))!)}><Code2 size={15}/>Копировать пример</button></div><p className="code-provenance">{file?.original?'Оригинальный файл · SHA-256 '+file.sha256.slice(0,16):'Файл подключения, подготовленный для Atlas'}</p><pre><code>{codeError||code||'Загрузка файла…'}</code></pre></div>}
 {tab==='install'&&<div className="component-install"><div><h3>1. Получите весь комплект</h3><p>Сохраните структуру файлов. В архиве есть исходники, стили, пример, инструкция и лицензия.</p><a className="primary-btn" href={'/components/'+selected.id+'/component.zip'} download={selected.id+'.zip'}><Download size={16}/>Скачать комплект</a></div><div><h3>2. Установите зависимости</h3><pre>{selected.installCommand}</pre>{selected.library!=='uiverse'&&<button className="secondary-btn" onClick={()=>void copy(selected.installCommand)}><Copy size={15}/>Копировать установку</button>}</div><div><h3>3. Подключите пример</h3><p>{selected.library==='uiverse'?'Готовый HTML файл содержит CSS. Его можно использовать без библиотек.':'Импортируйте demo.css в корневом layout, объедините пути из tsconfig.paths.json с вашими aliases. В Vite добавьте componentAliases из vite.config.fragment.mjs в resolve.alias. Для Next.js используйте NextExample.tsx; для React — Example.tsx. Полная инструкция находится в README.md.'}</p><p className="integration-note">Стили демонстрации рассчитаны на отдельную область. В существующем приложении переносите нужные токены и классы с учётом вашей темы.</p><button className="secondary-btn" onClick={()=>void copyFile(selected.exportFiles.find(f=>f.path==='README.md')!)}><Copy size={15}/>Копировать инструкцию</button></div><div><h3>Основа для передачи в Codex</h3><p>Короткий паспорт указывает на конкретные файлы этого компонента. Автоматическое подключение к Codex — следующий этап.</p><button className="secondary-btn" onClick={()=>void copy(JSON.stringify({component:selected.id,revision:selected.revision,sha256:selected.bundleHash,manifest:location.origin+'/components/'+selected.id+'/manifest.json',localPath:'public/components/'+selected.id+'/files',settings:applied},null,2))}><Copy size={15}/>Копировать паспорт</button></div></div>}
 {tab==='source'&&<div className="component-source-panel"><div><h3>Автор и происхождение</h3><p>{selected.author}</p><a href={selected.sourceUrl} target="_blank" rel="noreferrer">Оригинальный исходник <ExternalLink size={14}/></a><dl><dt>Ревизия</dt><dd>{selected.revision}</dd><dt>Лицензия</dt><dd>{selected.license}</dd><dt>SHA-256 комплекта</dt><dd>{selected.bundleHash}</dd></dl><a href={selected.licenseUrl} target="_blank" rel="noreferrer">Условия использования ↗</a><p>Реализация компонента сохранена без изменений. Текст, данные и оформление примера подключения подготовлены для Atlas. {selected.demoAssets?.length?'В скомпилированном демо внешние изображения заменены локальными SVG; оригинальные файлы сохранены полностью.':''}</p></div><label className="module-notes">Моя заметка<textarea maxLength={5000} value={data.components.notes[selected.id]||''} placeholder="Где я хочу применить этот компонент…" onChange={e=>{const id=selected.id,note=e.target.value;changeData(d=>({...d,components:{...d.components,notes:{...d.components.notes,[id]:note}}}))}}/><small>Сохраняется локально</small></label></div>}
 </div>
 {manualCopy&&<div className="manual-copy"><label>Скопируйте выделенный текст вручную<textarea ref={manualRef} readOnly value={manualCopy}/></label><button className="small-btn" onClick={()=>setManualCopy('')}>Закрыть</button></div>}
 <div className="component-dialog-footer"><span><Check size={14}/>Локальный комплект · {selected.exportFiles.length+1} файлов</span><a href={'/components/'+selected.id+'/component.zip'} download={selected.id+'.zip'}><Download size={15}/>Скачать комплект</a></div></>}
 </dialog>
 </section>;
}
