import raw from './components-data/catalog.json';
export type Control={key:string;label:string;type:'number'|'text'|'color';default:string|number;min?:number;max?:number;step?:number};
export type ComponentFile={path:string;sourcePath?:string;url:string;sha256:string;bytes:number;original?:boolean};
export type ComponentDescriptor={id:string;batch?:string;extra?:boolean;demoAssets?:{path:string;author:string;license:string;purpose:string}[];library:string;name:string;title:string;category:string;description:string;author:string;sourceUrl:string;libraryUrl:string;revision:string;license:string;licenseUrl:string;entry:string;runtimeEntry?:string;runtimeDemoEntry?:string;runtimeAliases?:Record<string,string>;files:ComponentFile[];exportFiles:ComponentFile[];typeDependencies?:string[];dependencies:string[];dependencyVersions:Record<string,string>;technologies:string[];formats:string[];heavy:boolean;performance:string;accessibility:string;keyboard:string;mobile:string;preview:string;poster:string;controls:Control[];defaults:Record<string,string|number>;installCommand:string;bundleHash:string};
export const components=raw as unknown as ComponentDescriptor[];
export const getComponent=(id:string)=>components.find(c=>c.id===id);
export const componentCategories:Record<string,string>={all:'Все',background:'Фоны',text:'Текст',cards:'Карточки',navigation:'Навигация',controls:'Управление',transitions:'Переходы'};
export const componentLibraries=[
 {id:'react-bits',title:'React Bits',url:'https://reactbits.dev',description:'Выразительные фоны, типографика, WebGL и тактильные микровзаимодействия.',license:'MIT + Commons Clause',note:'Личное и коммерческое использование в продуктах. У компонентов есть ограничения на распространение отдельно от продукта.',licenseUrl:'https://github.com/DavidHDev/react-bits/blob/main/LICENSE.md',color:'#8c70e6'},
 {id:'magic-ui',title:'Magic UI',url:'https://magicui.design/docs/components',description:'Анимированные карточки, кнопки, числа и графические эффекты.',license:'MIT',note:'Сохраняйте уведомление об авторстве и лицензию в копиях исходников.',licenseUrl:'https://github.com/magicuidesign/magicui/blob/main/LICENSE.md',color:'#cf9741'},
 {id:'animate-ui',title:'Animate UI',url:'https://animate-ui.com/docs/components',description:'Анимированные контролы, диалоги, навигация и готовые примеры.',license:'MIT',note:'Сохраняйте лицензию. Примеры включают вспомогательные UI компоненты.',licenseUrl:'https://github.com/imskyleen/animate-ui/blob/main/LICENSE.md',color:'#3ca183'},
 {id:'motion-primitives',title:'Motion Primitives',url:'https://motion-primitives.com/docs',description:'Переходы между состояниями, морфинг и расширяемые панели.',license:'MIT',note:'Сохраняйте уведомление об авторстве и лицензию.',licenseUrl:'https://github.com/ibelick/motion-primitives/blob/main/LICENCE.md',color:'#cf718f'},
 {id:'uiverse',title:'Uiverse',url:'https://uiverse.io',description:'Авторские HTML/CSS элементы: переключатели, поля, кнопки и загрузчики.',license:'MIT',note:'Автор каждого элемента указан отдельно; лицензия включена в комплект.',licenseUrl:'https://github.com/uiverse-io/galaxy/blob/main/LICENSE',color:'#5b93c6'},
 {id:'kokonut-ui',title:'Kokonut UI',url:'https://kokonutui.com/docs',description:'Тексты, навигация, стеклянные поверхности и выразительные микровзаимодействия.',license:'MIT',note:'Сохраняйте уведомление об авторстве и лицензию. В Atlas включены оригинальные исходники.',licenseUrl:'https://github.com/kokonut-labs/kokonutui/blob/main/LICENSE',color:'#cf984d'},
 {id:'smooth-ui',title:'SmoothUI',url:'https://smoothui.dev',description:'Dynamic Island, сфера помощника, свайп карточек и переходы между поверхностями.',license:'MIT',note:'Сохраняйте уведомление об авторстве и лицензию. В Atlas включены оригинальные исходники.',licenseUrl:'https://github.com/educlopez/smoothui/blob/main/LICENSE',color:'#d98165'},
 {id:'fancy-components',title:'Fancy Components',url:'https://www.fancycomponents.dev',description:'Физика Matter.js, притяжение к курсору, упругие линии и объёмная типографика.',license:'MIT',note:'Сохраняйте уведомление об авторстве и лицензию. В Atlas включены оригинальные исходники.',licenseUrl:'https://github.com/danielpetho/fancy/blob/main/LICENSE',color:'#bd6e9f'},
 {id:'cult-ui',title:'Cult UI',url:'https://www.cult-ui.com',description:'Панели с меняющейся высотой, направленные переходы и сортируемые списки.',license:'MIT',note:'Сохраняйте уведомление об авторстве и лицензию. В Atlas включены оригинальные исходники.',licenseUrl:'https://github.com/nolly-studio/cult-ui/blob/main/LICENSE.md',color:'#81a95b'},
 {id:'animata',title:'Animata',url:'https://animata.design',description:'Живые кнопки, раскрывающиеся меню и интерактивные виджеты.',license:'MIT',note:'Сохраняйте уведомление об авторстве и лицензию. В Atlas включены оригинальные исходники.',licenseUrl:'https://github.com/codse/animata/blob/main/LICENSE.md',color:'#519fae'},
 {id:'paper-shaders',title:'Paper Shaders',url:'https://shaders.paper.design',description:'Шесть материалов WebGL: жидкий металл, вода, капли, лучи, дым и потоки.',license:'Apache-2.0',note:'Сохраняйте LICENSE и NOTICE. Для изменённых файлов отмечайте изменения.',licenseUrl:'https://github.com/paper-design/shaders/blob/main/LICENSE',color:'#788fd0'},
 {id:'aceternity',title:'Aceternity UI',url:'https://ui.aceternity.com/components',description:'Карточки, параллакс, формы и интерактивные эффекты для React и Next.js.',license:'Aceternity License',note:'Внешний каталог. Бесплатные и Pro материалы имеют собственные условия использования; источники компонентов не распространяются через Atlas.',licenseUrl:'https://ui.aceternity.com/licence',color:'#706ad7'}
];

export const componentFeatured=['paper-shaders-liquid-metal','smooth-ui-dynamic-island','kokonut-ui-card-stack','react-bits-galaxy','fancy-components-text-letter-3d-swap','kokonut-ui-liquid-glass-card','fancy-components-physics-gravity','smooth-ui-siri-orb','paper-shaders-god-rays','kokonut-ui-morphic-navbar','paper-shaders-water','kokonut-ui-action-search-bar'];
