export const sources = {
  film: {title: 'Adobe · Правило 180 градусов', url: 'https://www.adobe.com/creativecloud/video/discover/what-is-the-180-degree-rule.html', note: 'Кинематографическая непрерывность. Перенос в интерфейс является аналогией.'},
  animation: {title: 'Adobe · 12 principles of animation', url: 'https://www.adobe.com/creativecloud/animation/discover/principles-of-animation.html', note: 'Классические принципы анимации. UI-примеры и пресеты адаптированы для каталога.'},
  aesthetic: {title: 'NN/g · Aesthetic–Usability Effect', url: 'https://www.nngroup.com/articles/aesthetic-usability-effect/', note: 'Восприятие удобства и реальная успешность задачи могут расходиться.'},
  familiar: {title: 'NN/g · Fresh vs. Familiar', url: 'https://www.nngroup.com/articles/fresh-vs-familiar-aggressive-redesign/', note: 'Ожидания пользователя и цена изменений привычного интерфейса.'},
  cognitive: {title: 'NN/g · Cognitive Load', url: 'https://www.nngroup.com/articles/minimize-cognitive-load/', note: 'Как структура, привычные модели и отсутствие лишних прерываний влияют на усилие.'},
  peak: {title: 'NN/g · Peak–End Rule', url: 'https://www.nngroup.com/articles/peak-end-rule/', note: 'Эвристика воспоминаний об опыте, а не инструкция игнорировать середину сценария.'},
  disclosure: {title: 'NN/g · Progressive Disclosure', url: 'https://www.nngroup.com/articles/progressive-disclosure/', note: 'Скрытие редких деталей требует сохранения обнаружимости и важных последствий.'},
  textSpacing: {title: 'W3C · Text Spacing', url: 'https://www.w3.org/WAI/WCAG22/Understanding/text-spacing.html', note: 'SC 1.4.12 · AA. Устойчивость содержания к пользовательским интервалам.'},
  dragging: {title: 'W3C · Dragging Movements', url: 'https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html', note: 'SC 2.5.7 · AA. Альтернатива перетаскиванию одним указателем, с исключениями.'},
  statusMessages: {title: 'W3C · Status Messages', url: 'https://www.w3.org/WAI/WCAG22/Understanding/status-messages.html', note: 'SC 4.1.3 · AA. Сообщение о состоянии можно определить программно без получения фокуса.'},
  useColor: {title: 'W3C · Use of Color', url: 'https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html', note: 'SC 1.4.1 · A. Цвет не должен быть единственным визуальным носителем смысла.'},
  wcag: {title: 'W3C · WCAG 2.2', url: 'https://www.w3.org/WAI/WCAG22/quickref/', note: 'Нормативные критерии доступности. У каждого критерия есть уровень и исключения.'},
  contrast: {title: 'W3C · Contrast (Minimum)', url: 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html', note: 'SC 1.4.3 · AA. Порог зависит от размера и начертания текста.'},
  target: {title: 'W3C · Target Size (Minimum)', url: 'https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html', note: 'SC 2.5.8 · AA. 24 CSS px с оговорёнными исключениями, включая достаточное расстояние.'},
  focus: {title: 'W3C · Focus Not Obscured', url: 'https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html', note: 'SC 2.4.11 · AA. Компонент в фокусе не должен быть полностью скрыт авторским контентом.'},
  reflow: {title: 'W3C · Reflow', url: 'https://www.w3.org/WAI/WCAG22/Understanding/reflow.html', note: 'SC 1.4.10 · AA. Вертикальный контент проверяют при ширине 320 CSS px; есть исключения.'},
  auth: {title: 'W3C · Accessible Authentication', url: 'https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum.html', note: 'SC 3.3.8 · AA. Когнитивные тесты при входе требуют альтернативы или механизма помощи.'},
  reduced: {title: 'W3C · Animation from Interactions', url: 'https://www.w3.org/WAI/WCAG22/Understanding/animation-from-interactions.html', note: 'SC 2.3.3 · AAA. Необязательную анимацию взаимодействий можно отключать.'},
  apg: {title: 'W3C · ARIA Authoring Practices', url: 'https://www.w3.org/WAI/ARIA/apg/patterns/', note: 'Информативные паттерны, роли и управление с клавиатуры; не отдельный стандарт соответствия.'},
  forms: {title: 'W3C · Forms Tutorial', url: 'https://www.w3.org/WAI/tutorials/forms/', note: 'Подписи, инструкции, группировка и обратная связь для форм.'},
  images: {title: 'W3C · Images Tutorial', url: 'https://www.w3.org/WAI/tutorials/images/', note: 'Текстовая альтернатива определяется назначением изображения.'},
  heuristics: {title: 'Jakob Nielsen · 10 эвристик', url: 'https://www.nngroup.com/articles/ten-usability-heuristics/', note: 'Рекомендации для экспертной оценки, а не универсальное доказательство удобства.'},
  proximity: {title: 'NN/g · Proximity', url: 'https://www.nngroup.com/articles/gestalt-proximity/', note: 'Близость элементов помогает выразить связь.'},
  recognition: {title: 'NN/g · Recognition & Recall', url: 'https://www.nngroup.com/articles/recognition-and-recall/', note: 'Видимые подсказки снижают необходимость вспоминать информацию.'},
  apple: {title: 'Apple · Human Interface Guidelines', url: 'https://developer.apple.com/design/human-interface-guidelines/', note: 'Рекомендации Apple. Веб-примеры в каталоге — учебные модели, не системные компоненты.'},
  appleMotion: {title: 'Apple · Motion', url: 'https://developer.apple.com/design/human-interface-guidelines/motion', note: 'Движение в интерфейсах Apple: обратная связь и пространственная связь.'},
  material: {title: 'Google · Material Design 3', url: 'https://m3.material.io/', note: 'Дизайн-система: компоненты, тональные роли, адаптивность и движение.'},
  materialMotion: {title: 'Material 3 · Motion', url: 'https://m3.material.io/styles/motion/overview/how-it-works', note: 'Модель движения Material. Значения в лаборатории — собственные учебные пресеты.'},
  androidTarget: {title: 'Google · Touch target size', url: 'https://support.google.com/accessibility/android/answer/7101858?hl=en', note: 'Рекомендация Android: область касания не меньше 48 × 48 dp.'},
  fluent: {title: 'Microsoft · Fluent 2', url: 'https://fluent2.microsoft.design/', note: 'Рекомендации и компоненты Microsoft для согласованных интерфейсов.'},
  carbon: {title: 'IBM · Carbon 2x Grid', url: 'https://www.carbondesignsystem.com/building-blocks/foundations/2x-grid/overview', note: 'Пример системной сетки IBM на базовой единице 8 px.'},
  atlassian: {title: 'Atlassian · Foundations', url: 'https://atlassian.design/foundations/', note: 'Пример организации цвета, типографики, иконок и токенов.'},
  govuk: {title: 'GOV.UK · Design System', url: 'https://design-system.service.gov.uk/', note: 'Практики понятных сервисов, форм и пользовательских сценариев.'},
  webdesign: {title: 'Google · Learn Responsive Design', url: 'https://web.dev/learn/design/', note: 'Адаптивность, типографика и способы ввода в вебе.'},
  vitals: {title: 'Google · Web Vitals', url: 'https://web.dev/articles/vitals', note: 'LCP, INP и CLS измеряют разные аспекты реального пользовательского опыта.'},
  thirds: {title: 'Adobe · Rule of Thirds', url: 'https://www.adobe.com/creativecloud/photography/technique/rule-of-thirds.html', note: 'Художественный ориентир из фотографии, допускающий осознанное нарушение.'},
  composition: {title: 'Adobe · Composition', url: 'https://www.adobe.com/creativecloud/photography/technique/composition.html', note: 'Контекст композиции в фотографии. Перенос в интерфейс — авторская интерпретация.'},
  tokens: {title: 'W3C Community · Design Tokens', url: 'https://www.w3.org/community/design-tokens/', note: 'Работа сообщества над форматом токенов; не WCAG и не рекомендация W3C.'},
  mdn: {title: 'MDN · CSS', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS', note: 'Справочник реализации. Он не устанавливает художественные правила.'},
  research: {title: 'IBM · Enterprise Design Thinking', url: 'https://www.ibm.com/design/thinking/', note: 'Рабочий процесс, ориентированный на результаты для людей.'},
  fitts: {title: 'Paul Fitts · исследование 1954', url: 'https://doi.org/10.1037/h0055392', note: 'Модель двигательного действия; применение к конкретному интерфейсу требует проверки.'},
  hick: {title: 'William Hick · исследование 1952', url: 'https://doi.org/10.1080/17470215208416600', note: 'Экспериментальная зависимость времени реакции от выбора, не запрет на длинные меню.'},
} as const;
export type SourceKey = keyof typeof sources;
