import * as React from 'react';
import { DropdownMenu as DropdownMenuPrimitive } from 'radix-ui';
import { type HTMLMotionProps } from 'motion/react';
import { type HighlightItemProps, type HighlightProps } from '../effects/highlight';
type DropdownMenuContextType = {
    isOpen: boolean;
    setIsOpen: (o: boolean) => void;
    highlightedValue: string | null;
    setHighlightedValue: (value: string | null) => void;
};
type DropdownMenuSubContextType = {
    isOpen: boolean;
    setIsOpen: (o: boolean) => void;
};
declare const useDropdownMenu: () => DropdownMenuContextType;
declare const useDropdownMenuSub: () => DropdownMenuSubContextType;
type DropdownMenuProps = React.ComponentProps<typeof DropdownMenuPrimitive.Root>;
declare function DropdownMenu(props: DropdownMenuProps): React.JSX.Element;
type DropdownMenuTriggerProps = React.ComponentProps<typeof DropdownMenuPrimitive.Trigger>;
declare function DropdownMenuTrigger(props: DropdownMenuTriggerProps): React.JSX.Element;
type DropdownMenuPortalProps = React.ComponentProps<typeof DropdownMenuPrimitive.Portal>;
declare function DropdownMenuPortal(props: DropdownMenuPortalProps): React.JSX.Element;
type DropdownMenuGroupProps = React.ComponentProps<typeof DropdownMenuPrimitive.Group>;
declare function DropdownMenuGroup(props: DropdownMenuGroupProps): React.JSX.Element;
type DropdownMenuSubProps = React.ComponentProps<typeof DropdownMenuPrimitive.Sub>;
declare function DropdownMenuSub(props: DropdownMenuSubProps): React.JSX.Element;
type DropdownMenuRadioGroupProps = React.ComponentProps<typeof DropdownMenuPrimitive.RadioGroup>;
declare function DropdownMenuRadioGroup(props: DropdownMenuRadioGroupProps): React.JSX.Element;
type DropdownMenuSubTriggerProps = Omit<React.ComponentProps<typeof DropdownMenuPrimitive.SubTrigger>, 'asChild'> & HTMLMotionProps<'div'>;
declare function DropdownMenuSubTrigger({ disabled, textValue, ...props }: DropdownMenuSubTriggerProps): React.JSX.Element;
type DropdownMenuSubContentProps = Omit<React.ComponentProps<typeof DropdownMenuPrimitive.SubContent>, 'forceMount' | 'asChild'> & Omit<React.ComponentProps<typeof DropdownMenuPrimitive.Portal>, 'forceMount'> & HTMLMotionProps<'div'>;
declare function DropdownMenuSubContent({ loop, onEscapeKeyDown, onPointerDownOutside, onFocusOutside, onInteractOutside, sideOffset, alignOffset, avoidCollisions, collisionBoundary, collisionPadding, arrowPadding, sticky, hideWhenDetached, transition, style, container, ...props }: DropdownMenuSubContentProps): React.JSX.Element;
type DropdownMenuHighlightProps = Omit<HighlightProps, 'controlledItems' | 'enabled' | 'hover'> & {
    animateOnHover?: boolean;
};
declare function DropdownMenuHighlight({ transition, ...props }: DropdownMenuHighlightProps): React.JSX.Element;
type DropdownMenuContentProps = Omit<React.ComponentProps<typeof DropdownMenuPrimitive.Content>, 'forceMount' | 'asChild'> & Omit<React.ComponentProps<typeof DropdownMenuPrimitive.Portal>, 'forceMount'> & HTMLMotionProps<'div'>;
declare function DropdownMenuContent({ loop, onCloseAutoFocus, onEscapeKeyDown, onPointerDownOutside, onFocusOutside, onInteractOutside, side, sideOffset, align, alignOffset, avoidCollisions, collisionBoundary, collisionPadding, arrowPadding, sticky, hideWhenDetached, transition, style, container, ...props }: DropdownMenuContentProps): React.JSX.Element;
type DropdownMenuHighlightItemProps = HighlightItemProps;
declare function DropdownMenuHighlightItem(props: DropdownMenuHighlightItemProps): React.JSX.Element;
type DropdownMenuItemProps = Omit<React.ComponentProps<typeof DropdownMenuPrimitive.Item>, 'asChild'> & HTMLMotionProps<'div'>;
declare function DropdownMenuItem({ disabled, onSelect, textValue, ...props }: DropdownMenuItemProps): React.JSX.Element;
type DropdownMenuCheckboxItemProps = Omit<React.ComponentProps<typeof DropdownMenuPrimitive.CheckboxItem>, 'asChild'> & HTMLMotionProps<'div'>;
declare function DropdownMenuCheckboxItem({ checked, onCheckedChange, disabled, onSelect, textValue, ...props }: DropdownMenuCheckboxItemProps): React.JSX.Element;
type DropdownMenuRadioItemProps = Omit<React.ComponentProps<typeof DropdownMenuPrimitive.RadioItem>, 'asChild'> & HTMLMotionProps<'div'>;
declare function DropdownMenuRadioItem({ value, disabled, onSelect, textValue, ...props }: DropdownMenuRadioItemProps): React.JSX.Element;
type DropdownMenuLabelProps = React.ComponentProps<typeof DropdownMenuPrimitive.Label>;
declare function DropdownMenuLabel(props: DropdownMenuLabelProps): React.JSX.Element;
type DropdownMenuSeparatorProps = React.ComponentProps<typeof DropdownMenuPrimitive.Separator>;
declare function DropdownMenuSeparator(props: DropdownMenuSeparatorProps): React.JSX.Element;
type DropdownMenuShortcutProps = React.ComponentProps<'span'>;
declare function DropdownMenuShortcut(props: DropdownMenuShortcutProps): React.JSX.Element;
type DropdownMenuItemIndicatorProps = Omit<React.ComponentProps<typeof DropdownMenuPrimitive.ItemIndicator>, 'asChild'> & HTMLMotionProps<'div'>;
declare function DropdownMenuItemIndicator(props: DropdownMenuItemIndicatorProps): React.JSX.Element;
export { DropdownMenu, DropdownMenuTrigger, DropdownMenuHighlight, DropdownMenuContent, DropdownMenuItem, DropdownMenuItemIndicator, DropdownMenuHighlightItem, DropdownMenuCheckboxItem, DropdownMenuRadioItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuGroup, DropdownMenuPortal, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuRadioGroup, useDropdownMenu, useDropdownMenuSub, type DropdownMenuProps, type DropdownMenuTriggerProps, type DropdownMenuHighlightProps, type DropdownMenuContentProps, type DropdownMenuItemProps, type DropdownMenuItemIndicatorProps, type DropdownMenuHighlightItemProps, type DropdownMenuCheckboxItemProps, type DropdownMenuRadioItemProps, type DropdownMenuLabelProps, type DropdownMenuSeparatorProps, type DropdownMenuShortcutProps, type DropdownMenuGroupProps, type DropdownMenuPortalProps, type DropdownMenuSubProps, type DropdownMenuSubContentProps, type DropdownMenuSubTriggerProps, type DropdownMenuRadioGroupProps, type DropdownMenuContextType, type DropdownMenuSubContextType, };
