import * as React from 'react';
import { type Transition, type HTMLMotionProps } from 'motion/react';
import { type WithAsChild } from '@/registry/primitives/animate/slot';
type Side = 'top' | 'bottom' | 'left' | 'right';
type Align = 'start' | 'center' | 'end';
type TooltipData = {
    contentProps: HTMLMotionProps<'div'>;
    contentAsChild: boolean;
    rect: DOMRect;
    side: Side;
    sideOffset: number;
    align: Align;
    alignOffset: number;
    id: string;
};
type GlobalTooltipContextType = {
    showTooltip: (data: TooltipData) => void;
    hideTooltip: () => void;
    hideImmediate: () => void;
    currentTooltip: TooltipData | null;
    transition: Transition;
    globalId: string;
    setReferenceEl: (el: HTMLElement | null) => void;
    referenceElRef: React.RefObject<HTMLElement | null>;
};
declare const useGlobalTooltip: () => GlobalTooltipContextType;
type TooltipContextType = {
    props: HTMLMotionProps<'div'>;
    setProps: React.Dispatch<React.SetStateAction<HTMLMotionProps<'div'>>>;
    asChild: boolean;
    setAsChild: React.Dispatch<React.SetStateAction<boolean>>;
    side: Side;
    sideOffset: number;
    align: Align;
    alignOffset: number;
    id: string;
};
declare const useTooltip: () => TooltipContextType;
type TooltipPosition = {
    x: number;
    y: number;
};
type TooltipProviderProps = {
    children: React.ReactNode;
    id?: string;
    openDelay?: number;
    closeDelay?: number;
    transition?: Transition;
};
declare function TooltipProvider({ children, id, openDelay, closeDelay, transition, }: TooltipProviderProps): React.JSX.Element;
declare const MotionTooltipArrow: React.ComponentType<Omit<{
    string?: string | number;
    ref?: React.Ref<SVGSVGElement>;
    filter?: string;
    fill?: string;
    slot?: string;
    clipPath?: string;
    mask?: string;
    path?: string;
    key?: React.Key;
    height?: number;
    name?: string;
    type?: string;
    width?: number;
    suppressHydrationWarning?: boolean;
    className?: string;
    id?: string;
    lang?: string;
    nonce?: string;
    tabIndex?: number;
    role?: React.AriaRole;
    color?: string;
    part?: string;
    "aria-activedescendant"?: string;
    "aria-atomic"?: boolean | "true" | "false";
    "aria-autocomplete"?: "list" | "none" | "inline" | "both";
    "aria-braillelabel"?: string;
    "aria-brailleroledescription"?: string;
    "aria-busy"?: boolean | "true" | "false";
    "aria-checked"?: boolean | "true" | "false" | "mixed";
    "aria-colcount"?: number;
    "aria-colindex"?: number;
    "aria-colindextext"?: string;
    "aria-colspan"?: number;
    "aria-controls"?: string;
    "aria-current"?: boolean | "time" | "step" | "page" | "true" | "false" | "location" | "date";
    "aria-describedby"?: string;
    "aria-description"?: string;
    "aria-details"?: string;
    "aria-disabled"?: boolean | "true" | "false";
    "aria-dropeffect"?: "link" | "none" | "copy" | "execute" | "move" | "popup";
    "aria-errormessage"?: string;
    "aria-expanded"?: boolean | "true" | "false";
    "aria-flowto"?: string;
    "aria-grabbed"?: boolean | "true" | "false";
    "aria-haspopup"?: boolean | "dialog" | "menu" | "grid" | "true" | "false" | "listbox" | "tree";
    "aria-hidden"?: boolean | "true" | "false";
    "aria-invalid"?: boolean | "true" | "false" | "grammar" | "spelling";
    "aria-keyshortcuts"?: string;
    "aria-label"?: string;
    "aria-labelledby"?: string;
    "aria-level"?: number;
    "aria-live"?: "off" | "assertive" | "polite";
    "aria-modal"?: boolean | "true" | "false";
    "aria-multiline"?: boolean | "true" | "false";
    "aria-multiselectable"?: boolean | "true" | "false";
    "aria-orientation"?: "horizontal" | "vertical";
    "aria-owns"?: string;
    "aria-placeholder"?: string;
    "aria-posinset"?: number;
    "aria-pressed"?: boolean | "true" | "false" | "mixed";
    "aria-readonly"?: boolean | "true" | "false";
    "aria-relevant"?: "text" | "all" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals";
    "aria-required"?: boolean | "true" | "false";
    "aria-roledescription"?: string;
    "aria-rowcount"?: number;
    "aria-rowindex"?: number;
    "aria-rowindextext"?: string;
    "aria-rowspan"?: number;
    "aria-selected"?: boolean | "true" | "false";
    "aria-setsize"?: number;
    "aria-sort"?: "none" | "ascending" | "descending" | "other";
    "aria-valuemax"?: number;
    "aria-valuemin"?: number;
    "aria-valuenow"?: number;
    "aria-valuetext"?: string;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    };
    onCopy?: React.ClipboardEventHandler<SVGSVGElement>;
    onCopyCapture?: React.ClipboardEventHandler<SVGSVGElement>;
    onCut?: React.ClipboardEventHandler<SVGSVGElement>;
    onCutCapture?: React.ClipboardEventHandler<SVGSVGElement>;
    onPaste?: React.ClipboardEventHandler<SVGSVGElement>;
    onPasteCapture?: React.ClipboardEventHandler<SVGSVGElement>;
    onCompositionEnd?: React.CompositionEventHandler<SVGSVGElement>;
    onCompositionEndCapture?: React.CompositionEventHandler<SVGSVGElement>;
    onCompositionStart?: React.CompositionEventHandler<SVGSVGElement>;
    onCompositionStartCapture?: React.CompositionEventHandler<SVGSVGElement>;
    onCompositionUpdate?: React.CompositionEventHandler<SVGSVGElement>;
    onCompositionUpdateCapture?: React.CompositionEventHandler<SVGSVGElement>;
    onFocus?: React.FocusEventHandler<SVGSVGElement>;
    onFocusCapture?: React.FocusEventHandler<SVGSVGElement>;
    onBlur?: React.FocusEventHandler<SVGSVGElement>;
    onBlurCapture?: React.FocusEventHandler<SVGSVGElement>;
    onChange?: React.ChangeEventHandler<SVGSVGElement, Element>;
    onChangeCapture?: React.ChangeEventHandler<SVGSVGElement, Element>;
    onBeforeInput?: React.InputEventHandler<SVGSVGElement>;
    onBeforeInputCapture?: React.InputEventHandler<SVGSVGElement>;
    onInput?: React.InputEventHandler<SVGSVGElement>;
    onInputCapture?: React.InputEventHandler<SVGSVGElement>;
    onReset?: React.ReactEventHandler<SVGSVGElement>;
    onResetCapture?: React.ReactEventHandler<SVGSVGElement>;
    onSubmit?: React.SubmitEventHandler<SVGSVGElement>;
    onSubmitCapture?: React.SubmitEventHandler<SVGSVGElement>;
    onInvalid?: React.ReactEventHandler<SVGSVGElement>;
    onInvalidCapture?: React.ReactEventHandler<SVGSVGElement>;
    onLoad?: React.ReactEventHandler<SVGSVGElement>;
    onLoadCapture?: React.ReactEventHandler<SVGSVGElement>;
    onError?: React.ReactEventHandler<SVGSVGElement>;
    onErrorCapture?: React.ReactEventHandler<SVGSVGElement>;
    onKeyDown?: React.KeyboardEventHandler<SVGSVGElement>;
    onKeyDownCapture?: React.KeyboardEventHandler<SVGSVGElement>;
    onKeyPress?: React.KeyboardEventHandler<SVGSVGElement>;
    onKeyPressCapture?: React.KeyboardEventHandler<SVGSVGElement>;
    onKeyUp?: React.KeyboardEventHandler<SVGSVGElement>;
    onKeyUpCapture?: React.KeyboardEventHandler<SVGSVGElement>;
    onAbort?: React.ReactEventHandler<SVGSVGElement>;
    onAbortCapture?: React.ReactEventHandler<SVGSVGElement>;
    onCanPlay?: React.ReactEventHandler<SVGSVGElement>;
    onCanPlayCapture?: React.ReactEventHandler<SVGSVGElement>;
    onCanPlayThrough?: React.ReactEventHandler<SVGSVGElement>;
    onCanPlayThroughCapture?: React.ReactEventHandler<SVGSVGElement>;
    onDurationChange?: React.ReactEventHandler<SVGSVGElement>;
    onDurationChangeCapture?: React.ReactEventHandler<SVGSVGElement>;
    onEmptied?: React.ReactEventHandler<SVGSVGElement>;
    onEmptiedCapture?: React.ReactEventHandler<SVGSVGElement>;
    onEncrypted?: React.ReactEventHandler<SVGSVGElement>;
    onEncryptedCapture?: React.ReactEventHandler<SVGSVGElement>;
    onEnded?: React.ReactEventHandler<SVGSVGElement>;
    onEndedCapture?: React.ReactEventHandler<SVGSVGElement>;
    onLoadedData?: React.ReactEventHandler<SVGSVGElement>;
    onLoadedDataCapture?: React.ReactEventHandler<SVGSVGElement>;
    onLoadedMetadata?: React.ReactEventHandler<SVGSVGElement>;
    onLoadedMetadataCapture?: React.ReactEventHandler<SVGSVGElement>;
    onLoadStart?: React.ReactEventHandler<SVGSVGElement>;
    onLoadStartCapture?: React.ReactEventHandler<SVGSVGElement>;
    onPause?: React.ReactEventHandler<SVGSVGElement>;
    onPauseCapture?: React.ReactEventHandler<SVGSVGElement>;
    onPlay?: React.ReactEventHandler<SVGSVGElement>;
    onPlayCapture?: React.ReactEventHandler<SVGSVGElement>;
    onPlaying?: React.ReactEventHandler<SVGSVGElement>;
    onPlayingCapture?: React.ReactEventHandler<SVGSVGElement>;
    onProgress?: React.ReactEventHandler<SVGSVGElement>;
    onProgressCapture?: React.ReactEventHandler<SVGSVGElement>;
    onRateChange?: React.ReactEventHandler<SVGSVGElement>;
    onRateChangeCapture?: React.ReactEventHandler<SVGSVGElement>;
    onSeeked?: React.ReactEventHandler<SVGSVGElement>;
    onSeekedCapture?: React.ReactEventHandler<SVGSVGElement>;
    onSeeking?: React.ReactEventHandler<SVGSVGElement>;
    onSeekingCapture?: React.ReactEventHandler<SVGSVGElement>;
    onStalled?: React.ReactEventHandler<SVGSVGElement>;
    onStalledCapture?: React.ReactEventHandler<SVGSVGElement>;
    onSuspend?: React.ReactEventHandler<SVGSVGElement>;
    onSuspendCapture?: React.ReactEventHandler<SVGSVGElement>;
    onTimeUpdate?: React.ReactEventHandler<SVGSVGElement>;
    onTimeUpdateCapture?: React.ReactEventHandler<SVGSVGElement>;
    onVolumeChange?: React.ReactEventHandler<SVGSVGElement>;
    onVolumeChangeCapture?: React.ReactEventHandler<SVGSVGElement>;
    onWaiting?: React.ReactEventHandler<SVGSVGElement>;
    onWaitingCapture?: React.ReactEventHandler<SVGSVGElement>;
    onAuxClick?: React.MouseEventHandler<SVGSVGElement>;
    onAuxClickCapture?: React.MouseEventHandler<SVGSVGElement>;
    onClick?: React.MouseEventHandler<SVGSVGElement>;
    onClickCapture?: React.MouseEventHandler<SVGSVGElement>;
    onContextMenu?: React.MouseEventHandler<SVGSVGElement>;
    onContextMenuCapture?: React.MouseEventHandler<SVGSVGElement>;
    onDoubleClick?: React.MouseEventHandler<SVGSVGElement>;
    onDoubleClickCapture?: React.MouseEventHandler<SVGSVGElement>;
    onDragCapture?: React.DragEventHandler<SVGSVGElement>;
    onDragEndCapture?: React.DragEventHandler<SVGSVGElement>;
    onDragEnter?: React.DragEventHandler<SVGSVGElement>;
    onDragEnterCapture?: React.DragEventHandler<SVGSVGElement>;
    onDragExit?: React.DragEventHandler<SVGSVGElement>;
    onDragExitCapture?: React.DragEventHandler<SVGSVGElement>;
    onDragLeave?: React.DragEventHandler<SVGSVGElement>;
    onDragLeaveCapture?: React.DragEventHandler<SVGSVGElement>;
    onDragOver?: React.DragEventHandler<SVGSVGElement>;
    onDragOverCapture?: React.DragEventHandler<SVGSVGElement>;
    onDragStartCapture?: React.DragEventHandler<SVGSVGElement>;
    onDrop?: React.DragEventHandler<SVGSVGElement>;
    onDropCapture?: React.DragEventHandler<SVGSVGElement>;
    onMouseDown?: React.MouseEventHandler<SVGSVGElement>;
    onMouseDownCapture?: React.MouseEventHandler<SVGSVGElement>;
    onMouseEnter?: React.MouseEventHandler<SVGSVGElement>;
    onMouseLeave?: React.MouseEventHandler<SVGSVGElement>;
    onMouseMove?: React.MouseEventHandler<SVGSVGElement>;
    onMouseMoveCapture?: React.MouseEventHandler<SVGSVGElement>;
    onMouseOut?: React.MouseEventHandler<SVGSVGElement>;
    onMouseOutCapture?: React.MouseEventHandler<SVGSVGElement>;
    onMouseOver?: React.MouseEventHandler<SVGSVGElement>;
    onMouseOverCapture?: React.MouseEventHandler<SVGSVGElement>;
    onMouseUp?: React.MouseEventHandler<SVGSVGElement>;
    onMouseUpCapture?: React.MouseEventHandler<SVGSVGElement>;
    onSelect?: React.ReactEventHandler<SVGSVGElement>;
    onSelectCapture?: React.ReactEventHandler<SVGSVGElement>;
    onTouchCancel?: React.TouchEventHandler<SVGSVGElement>;
    onTouchCancelCapture?: React.TouchEventHandler<SVGSVGElement>;
    onTouchEnd?: React.TouchEventHandler<SVGSVGElement>;
    onTouchEndCapture?: React.TouchEventHandler<SVGSVGElement>;
    onTouchMove?: React.TouchEventHandler<SVGSVGElement>;
    onTouchMoveCapture?: React.TouchEventHandler<SVGSVGElement>;
    onTouchStart?: React.TouchEventHandler<SVGSVGElement>;
    onTouchStartCapture?: React.TouchEventHandler<SVGSVGElement>;
    onPointerDown?: React.PointerEventHandler<SVGSVGElement>;
    onPointerDownCapture?: React.PointerEventHandler<SVGSVGElement>;
    onPointerMove?: React.PointerEventHandler<SVGSVGElement>;
    onPointerMoveCapture?: React.PointerEventHandler<SVGSVGElement>;
    onPointerUp?: React.PointerEventHandler<SVGSVGElement>;
    onPointerUpCapture?: React.PointerEventHandler<SVGSVGElement>;
    onPointerCancel?: React.PointerEventHandler<SVGSVGElement>;
    onPointerCancelCapture?: React.PointerEventHandler<SVGSVGElement>;
    onPointerEnter?: React.PointerEventHandler<SVGSVGElement>;
    onPointerLeave?: React.PointerEventHandler<SVGSVGElement>;
    onPointerOver?: React.PointerEventHandler<SVGSVGElement>;
    onPointerOverCapture?: React.PointerEventHandler<SVGSVGElement>;
    onPointerOut?: React.PointerEventHandler<SVGSVGElement>;
    onPointerOutCapture?: React.PointerEventHandler<SVGSVGElement>;
    onGotPointerCapture?: React.PointerEventHandler<SVGSVGElement>;
    onGotPointerCaptureCapture?: React.PointerEventHandler<SVGSVGElement>;
    onLostPointerCapture?: React.PointerEventHandler<SVGSVGElement>;
    onLostPointerCaptureCapture?: React.PointerEventHandler<SVGSVGElement>;
    onScroll?: React.UIEventHandler<SVGSVGElement>;
    onScrollCapture?: React.UIEventHandler<SVGSVGElement>;
    onScrollEnd?: React.UIEventHandler<SVGSVGElement>;
    onScrollEndCapture?: React.UIEventHandler<SVGSVGElement>;
    onWheel?: React.WheelEventHandler<SVGSVGElement>;
    onWheelCapture?: React.WheelEventHandler<SVGSVGElement>;
    onAnimationStartCapture?: React.AnimationEventHandler<SVGSVGElement>;
    onAnimationEnd?: React.AnimationEventHandler<SVGSVGElement>;
    onAnimationEndCapture?: React.AnimationEventHandler<SVGSVGElement>;
    onAnimationIteration?: React.AnimationEventHandler<SVGSVGElement>;
    onAnimationIterationCapture?: React.AnimationEventHandler<SVGSVGElement>;
    onToggle?: React.ToggleEventHandler<SVGSVGElement>;
    onBeforeToggle?: React.ToggleEventHandler<SVGSVGElement>;
    onTransitionCancel?: React.TransitionEventHandler<SVGSVGElement>;
    onTransitionCancelCapture?: React.TransitionEventHandler<SVGSVGElement>;
    onTransitionEnd?: React.TransitionEventHandler<SVGSVGElement>;
    onTransitionEndCapture?: React.TransitionEventHandler<SVGSVGElement>;
    onTransitionRun?: React.TransitionEventHandler<SVGSVGElement>;
    onTransitionRunCapture?: React.TransitionEventHandler<SVGSVGElement>;
    onTransitionStart?: React.TransitionEventHandler<SVGSVGElement>;
    onTransitionStartCapture?: React.TransitionEventHandler<SVGSVGElement>;
    crossOrigin?: "" | "anonymous" | "use-credentials";
    href?: string;
    media?: string;
    max?: string | number;
    min?: string | number;
    target?: string;
    method?: string;
    rotate?: string | number;
    scale?: string | number;
    x?: string | number;
    y?: string | number;
    z?: string | number;
    alignmentBaseline?: "inherit" | "alphabetic" | "hanging" | "ideographic" | "mathematical" | "auto" | "baseline" | "central" | "middle" | "text-after-edge" | "text-before-edge" | "before-edge" | "after-edge";
    baselineShift?: string | number;
    clipRule?: string | number;
    colorInterpolationFilters?: "inherit" | "auto" | "linearRGB" | "sRGB";
    cursor?: string | number;
    cx?: string | number;
    cy?: string | number;
    d?: string;
    direction?: string | number;
    display?: string | number;
    dominantBaseline?: "inherit" | "alphabetic" | "hanging" | "ideographic" | "mathematical" | "auto" | "central" | "middle" | "text-after-edge" | "text-before-edge" | "use-script" | "no-change" | "reset-size";
    fillOpacity?: string | number;
    fillRule?: "inherit" | "evenodd" | "nonzero";
    floodColor?: string | number;
    floodOpacity?: string | number;
    fontFamily?: string;
    fontSize?: string | number;
    fontSizeAdjust?: string | number;
    fontStyle?: string | number;
    fontVariant?: string | number;
    fontWeight?: string | number;
    imageRendering?: string | number;
    letterSpacing?: string | number;
    lightingColor?: string | number;
    markerEnd?: string;
    markerMid?: string;
    markerStart?: string;
    opacity?: string | number;
    order?: string | number;
    paintOrder?: string | number;
    pointerEvents?: string | number;
    r?: string | number;
    rx?: string | number;
    ry?: string | number;
    shapeRendering?: string | number;
    stopColor?: string;
    stopOpacity?: string | number;
    stroke?: string;
    strokeDasharray?: string | number;
    strokeDashoffset?: string | number;
    strokeLinecap?: "inherit" | "round" | "butt" | "square";
    strokeLinejoin?: "inherit" | "round" | "bevel" | "miter";
    strokeMiterlimit?: string | number;
    strokeOpacity?: string | number;
    strokeWidth?: number;
    textAnchor?: "inherit" | "start" | "end" | "middle";
    textRendering?: string | number;
    transform?: string;
    unicodeBidi?: string | number;
    vectorEffect?: string | number;
    visibility?: string | number;
    wordSpacing?: string | number;
    writingMode?: string | number;
    offset?: string | number;
    overflow?: string | number;
    textDecoration?: string | number;
    clip?: string | number;
    fontStretch?: string | number;
    colorInterpolation?: string | number;
    colorRendering?: string | number;
    glyphOrientationVertical?: string | number;
    pathLength?: string | number;
    from?: string | number;
    accentHeight?: string | number;
    accumulate?: "none" | "sum";
    additive?: "replace" | "sum";
    allowReorder?: "yes" | "no";
    alphabetic?: string | number;
    amplitude?: string | number;
    arabicForm?: "initial" | "medial" | "terminal" | "isolated";
    ascent?: string | number;
    attributeName?: string;
    attributeType?: string;
    autoReverse?: boolean | "true" | "false";
    azimuth?: string | number;
    baseFrequency?: string | number;
    baseProfile?: string | number;
    bbox?: string | number;
    begin?: string | number;
    bias?: string | number;
    by?: string | number;
    calcMode?: string | number;
    capHeight?: string | number;
    clipPathUnits?: string | number;
    colorProfile?: string | number;
    contentScriptType?: string | number;
    contentStyleType?: string | number;
    decelerate?: string | number;
    descent?: string | number;
    diffuseConstant?: string | number;
    divisor?: string | number;
    dur?: string | number;
    dx?: string | number;
    dy?: string | number;
    edgeMode?: string | number;
    elevation?: string | number;
    enableBackground?: string | number;
    end?: string | number;
    exponent?: string | number;
    externalResourcesRequired?: boolean | "true" | "false";
    filterRes?: string | number;
    filterUnits?: string | number;
    focusable?: (boolean | "true" | "false") | "auto";
    format?: string | number;
    fr?: string | number;
    fx?: string | number;
    fy?: string | number;
    g1?: string | number;
    g2?: string | number;
    glyphName?: string | number;
    glyphOrientationHorizontal?: string | number;
    glyphRef?: string | number;
    gradientTransform?: string;
    gradientUnits?: string;
    hanging?: string | number;
    horizAdvX?: string | number;
    horizOriginX?: string | number;
    ideographic?: string | number;
    in2?: string | number;
    in?: string;
    intercept?: string | number;
    k1?: string | number;
    k2?: string | number;
    k3?: string | number;
    k4?: string | number;
    k?: string | number;
    kernelMatrix?: string | number;
    kernelUnitLength?: string | number;
    kerning?: string | number;
    keyPoints?: string | number;
    keySplines?: string | number;
    keyTimes?: string | number;
    lengthAdjust?: string | number;
    limitingConeAngle?: string | number;
    local?: string | number;
    markerHeight?: string | number;
    markerUnits?: string | number;
    markerWidth?: string | number;
    maskContentUnits?: string | number;
    maskUnits?: string | number;
    mathematical?: string | number;
    mode?: string | number;
    numOctaves?: string | number;
    operator?: string | number;
    orient?: string | number;
    orientation?: string | number;
    origin?: string | number;
    overlinePosition?: string | number;
    overlineThickness?: string | number;
    panose1?: string | number;
    patternContentUnits?: string;
    patternTransform?: string | number;
    patternUnits?: string;
    points?: string;
    pointsAtX?: string | number;
    pointsAtY?: string | number;
    pointsAtZ?: string | number;
    preserveAlpha?: boolean | "true" | "false";
    preserveAspectRatio?: string;
    primitiveUnits?: string | number;
    radius?: string | number;
    refX?: string | number;
    refY?: string | number;
    renderingIntent?: string | number;
    repeatCount?: string | number;
    repeatDur?: string | number;
    requiredExtensions?: string | number;
    requiredFeatures?: string | number;
    restart?: string | number;
    result?: string;
    seed?: string | number;
    slope?: string | number;
    spacing?: string | number;
    specularConstant?: string | number;
    specularExponent?: string | number;
    speed?: string | number;
    spreadMethod?: string;
    startOffset?: string | number;
    stdDeviation?: string | number;
    stemh?: string | number;
    stemv?: string | number;
    stitchTiles?: string | number;
    strikethroughPosition?: string | number;
    strikethroughThickness?: string | number;
    surfaceScale?: string | number;
    systemLanguage?: string | number;
    tableValues?: string | number;
    targetX?: string | number;
    targetY?: string | number;
    textLength?: string | number;
    to?: string | number;
    u1?: string | number;
    u2?: string | number;
    underlinePosition?: string | number;
    underlineThickness?: string | number;
    unicode?: string | number;
    unicodeRange?: string | number;
    unitsPerEm?: string | number;
    vAlphabetic?: string | number;
    version?: string;
    vertAdvY?: string | number;
    vertOriginX?: string | number;
    vertOriginY?: string | number;
    vHanging?: string | number;
    vIdeographic?: string | number;
    viewBox?: string;
    viewTarget?: string | number;
    vMathematical?: string | number;
    widths?: string | number;
    x1?: string | number;
    x2?: string | number;
    xChannelSelector?: string;
    xHeight?: string | number;
    xlinkActuate?: string;
    xlinkArcrole?: string;
    xlinkHref?: string;
    xlinkRole?: string;
    xlinkShow?: string;
    xlinkTitle?: string;
    xlinkType?: string;
    xmlBase?: string;
    xmlLang?: string;
    xmlns?: string;
    xmlnsXlink?: string;
    xmlSpace?: string;
    y1?: string | number;
    y2?: string | number;
    yChannelSelector?: string;
    zoomAndPan?: string;
    context?: Omit<import("@floating-ui/react").FloatingContext<import("@floating-ui/react").ReferenceType>, "refs"> & {
        refs: any;
    };
    tipRadius?: number;
    staticOffset?: string | number;
} & import("framer-motion").MotionProps, "children"> & {
    children?: React.ReactNode | import("motion-dom").MotionValue<number> | import("motion-dom").MotionValue<string>;
}>;
type TooltipArrowProps = Omit<React.ComponentProps<typeof MotionTooltipArrow>, 'context'> & {
    withTransition?: boolean;
};
declare function TooltipArrow({ ref, withTransition, ...props }: TooltipArrowProps): React.JSX.Element;
type TooltipProps = {
    children: React.ReactNode;
    side?: Side;
    sideOffset?: number;
    align?: Align;
    alignOffset?: number;
};
declare function Tooltip({ children, side, sideOffset, align, alignOffset, }: TooltipProps): React.JSX.Element;
type TooltipContentProps = WithAsChild<HTMLMotionProps<'div'>>;
declare function TooltipContent({ asChild, ...props }: TooltipContentProps): any;
type TooltipTriggerProps = WithAsChild<HTMLMotionProps<'div'>>;
declare function TooltipTrigger({ ref, onMouseEnter, onMouseLeave, onFocus, onBlur, onPointerDown, asChild, ...props }: TooltipTriggerProps): React.JSX.Element;
export { TooltipProvider, Tooltip, TooltipContent, TooltipTrigger, TooltipArrow, useGlobalTooltip, useTooltip, type TooltipProviderProps, type TooltipProps, type TooltipContentProps, type TooltipTriggerProps, type TooltipArrowProps, type TooltipPosition, type GlobalTooltipContextType, type TooltipContextType, };
