'use client';
import React,{useState,useRef} from 'react';
import {FamilyDrawerRoot,FamilyDrawerTrigger,FamilyDrawerPortal,FamilyDrawerOverlay,FamilyDrawerContent,FamilyDrawerTitle,FamilyDrawerDescription,FamilyDrawerAnimatedWrapper,FamilyDrawerAnimatedContent,FamilyDrawerViewContent,FamilyDrawerButton,FamilyDrawerSecondaryButton,FamilyDrawerClose,useFamilyDrawer} from "./runtime/registry/default/ui/family-drawer";
function MenuView(){const {setView}=useFamilyDrawer();return <div className="p-2"><FamilyDrawerTitle className="text-2xl font-semibold mb-2">Your little collection</FamilyDrawerTitle><FamilyDrawerDescription className="mb-5 text-sm">A panel that grows with each view.</FamilyDrawerDescription><FamilyDrawerButton onClick={()=>setView('settings')}>Personal settings ↗</FamilyDrawerButton><FamilyDrawerButton onClick={()=>setView('story')}>A closer look ↗</FamilyDrawerButton><FamilyDrawerClose /></div>}
function SettingsView(){const {setView}=useFamilyDrawer();return <div className="p-2"><FamilyDrawerTitle className="text-2xl mb-3">Make it yours.</FamilyDrawerTitle><FamilyDrawerDescription className="mb-5">Preferences for this example.</FamilyDrawerDescription><label className="flex justify-between py-4">Quiet mode<input type="checkbox" defaultChecked/></label><label className="flex justify-between py-4">A little colour<input type="checkbox"/></label><FamilyDrawerSecondaryButton className="bg-secondary text-secondary-foreground" onClick={()=>setView('default')}>← Back</FamilyDrawerSecondaryButton></div>}
function StoryView(){const {setView}=useFamilyDrawer();return <div className="p-2"><FamilyDrawerTitle className="text-3xl mb-4">A different size.<br/>The same surface.</FamilyDrawerTitle><FamilyDrawerDescription className="mb-6 leading-relaxed">Shared layout and measured height connect each screen. A compact menu unfolds into a space for a longer story.</FamilyDrawerDescription><div className="drawer-art">✦</div><FamilyDrawerSecondaryButton className="bg-secondary text-secondary-foreground" onClick={()=>setView('default')}>← Back</FamilyDrawerSecondaryButton></div>}
export default function Example({settings={}}:{settings?:Record<string,any>}){
const p={...{"text":"Design in motion.","speed":1,"accent":"#b6a1ff","density":1,"waves":0.5,"distortion":0.15,"gravity":1,"threshold":110},...settings};
const [feedback,setFeedback]=useState('');

return <><div className="demo-layout"><FamilyDrawerRoot views={{default:MenuView,settings:SettingsView,story:StoryView}}><FamilyDrawerTrigger asChild><button className="demo-button">Open a little world ↗</button></FamilyDrawerTrigger><FamilyDrawerPortal><FamilyDrawerOverlay/><FamilyDrawerContent><FamilyDrawerAnimatedWrapper><FamilyDrawerAnimatedContent><FamilyDrawerViewContent/></FamilyDrawerAnimatedContent></FamilyDrawerAnimatedWrapper></FamilyDrawerContent></FamilyDrawerPortal></FamilyDrawerRoot></div>{feedback&&<output className="demo-feedback" aria-live="polite">{feedback}</output>}</>;
}
